package postgres

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

const postgresStateSchemaVersion = 1

const postgresSchemaAdvisoryLock int64 = 0x41674753746f7265

var postgresStateSchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS ag_storage_schema (
		component TEXT PRIMARY KEY,
		version INTEGER NOT NULL
	)`,
	`INSERT INTO ag_storage_schema (component, version)
		VALUES ('state', 1)
		ON CONFLICT (component) DO NOTHING`,
	`CREATE TABLE IF NOT EXISTS ag_trajectories (
		namespace TEXT NOT NULL,
		id TEXT NOT NULL,
		schema_version INTEGER NOT NULL,
		parent_id TEXT NOT NULL DEFAULT '',
		parent_entry_id TEXT NOT NULL DEFAULT '',
		created_at TIMESTAMPTZ NOT NULL,
		updated_at TIMESTAMPTZ NOT NULL,
		head TEXT NOT NULL DEFAULT '',
		checkpoint TEXT NOT NULL DEFAULT '',
		environment JSONB NOT NULL,
		inherited_entry_count BIGINT NOT NULL,
		owned_entry_count BIGINT NOT NULL,
		PRIMARY KEY (namespace, id)
	)`,
	`CREATE TABLE IF NOT EXISTS ag_trajectory_executions (
		namespace TEXT NOT NULL,
		trajectory_id TEXT NOT NULL,
		execution_id TEXT NOT NULL,
		state TEXT NOT NULL,
		revision BIGINT NOT NULL,
		base_head TEXT NOT NULL DEFAULT '',
		input_entry_id TEXT NOT NULL,
		provider TEXT NOT NULL DEFAULT '',
		system_prompt TEXT NOT NULL DEFAULT '',
		max_turns INTEGER NOT NULL,
		owner TEXT NOT NULL DEFAULT '',
		lease_token TEXT NOT NULL DEFAULT '',
		lease_expires_at TIMESTAMPTZ,
		last_error TEXT NOT NULL DEFAULT '',
		created_at TIMESTAMPTZ NOT NULL,
		updated_at TIMESTAMPTZ NOT NULL,
		PRIMARY KEY (namespace, trajectory_id),
		UNIQUE (namespace, execution_id),
		FOREIGN KEY (namespace, trajectory_id)
			REFERENCES ag_trajectories (namespace, id)
			ON DELETE CASCADE
	)`,
	`CREATE TABLE IF NOT EXISTS ag_trajectory_entries (
		namespace TEXT NOT NULL,
		trajectory_id TEXT NOT NULL,
		entry_id TEXT NOT NULL,
		parent_id TEXT NOT NULL DEFAULT '',
		ordinal BIGINT NOT NULL,
		depth BIGINT NOT NULL,
		kind TEXT NOT NULL,
		recorded_at TIMESTAMPTZ NOT NULL,
		generation BIGINT NOT NULL,
		execution_id TEXT NOT NULL DEFAULT '',
		operation_key TEXT NOT NULL DEFAULT '',
		turn INTEGER,
		correlation_id TEXT NOT NULL DEFAULT '',
		provider TEXT NOT NULL DEFAULT '',
		model TEXT NOT NULL DEFAULT '',
		tool_name TEXT NOT NULL DEFAULT '',
		tool_call_id TEXT NOT NULL DEFAULT '',
		finish_reason TEXT NOT NULL DEFAULT '',
		input_tokens BIGINT NOT NULL,
		output_tokens BIGINT NOT NULL,
		is_error BOOLEAN,
		cause_code TEXT NOT NULL DEFAULT '',
		action_kind TEXT NOT NULL DEFAULT '',
		payload_version INTEGER NOT NULL,
		payload BYTEA NOT NULL,
		attributes JSONB,
		audit JSONB,
		PRIMARY KEY (namespace, trajectory_id, entry_id),
		UNIQUE (namespace, trajectory_id, ordinal),
		FOREIGN KEY (namespace, trajectory_id)
			REFERENCES ag_trajectories (namespace, id)
			ON DELETE CASCADE
	)`,
	`ALTER TABLE ag_trajectory_entries
		ADD COLUMN IF NOT EXISTS audit JSONB`,
	`CREATE TABLE IF NOT EXISTS ag_operations (
		namespace TEXT NOT NULL,
		id TEXT NOT NULL,
		idempotency_key TEXT NOT NULL,
		kind TEXT NOT NULL,
		resource TEXT NOT NULL,
		resource_revision TEXT NOT NULL DEFAULT '',
		state TEXT NOT NULL,
		revision BIGINT NOT NULL,
		input BYTEA NOT NULL,
		invocation JSONB NOT NULL DEFAULT '{}',
		output BYTEA,
		operation_error TEXT NOT NULL DEFAULT '',
		submitted_at TIMESTAMPTZ NOT NULL,
		updated_at TIMESTAMPTZ NOT NULL,
		lease_owner TEXT NOT NULL DEFAULT '',
		lease_token TEXT NOT NULL DEFAULT '',
		lease_expires_at TIMESTAMPTZ,
		PRIMARY KEY (namespace, id),
		UNIQUE (
			namespace,
			kind,
			resource,
			resource_revision,
			idempotency_key
		)
	)`,
	`ALTER TABLE ag_operations
		ADD COLUMN IF NOT EXISTS invocation JSONB NOT NULL DEFAULT '{}'`,
	`CREATE TABLE IF NOT EXISTS ag_deliveries (
		namespace TEXT NOT NULL,
		queue TEXT NOT NULL,
		id TEXT NOT NULL,
		sequence BIGINT GENERATED BY DEFAULT AS IDENTITY,
		plugin TEXT NOT NULL,
		plugin_version TEXT NOT NULL DEFAULT '',
		subscription TEXT NOT NULL,
		resource_revision TEXT NOT NULL DEFAULT '',
		partition_key TEXT NOT NULL DEFAULT '',
		event_id TEXT NOT NULL,
		event_name TEXT NOT NULL,
		event_session_id TEXT NOT NULL DEFAULT '',
		event_generation BIGINT NOT NULL,
		event_payload BYTEA NOT NULL,
		state TEXT NOT NULL,
		attempt INTEGER NOT NULL,
		available_at TIMESTAMPTZ,
		lease_token TEXT NOT NULL DEFAULT '',
		lease_expires_at TIMESTAMPTZ,
		last_error TEXT NOT NULL DEFAULT '',
		created_at TIMESTAMPTZ NOT NULL,
		updated_at TIMESTAMPTZ NOT NULL,
		PRIMARY KEY (namespace, queue, id),
		UNIQUE (sequence)
	)`,
	`ALTER TABLE ag_deliveries
		ALTER COLUMN available_at DROP NOT NULL`,
	`CREATE INDEX IF NOT EXISTS ag_trajectories_updated_idx
		ON ag_trajectories (namespace, updated_at, id)`,
	`CREATE INDEX IF NOT EXISTS ag_trajectories_parent_idx
		ON ag_trajectories (namespace, parent_id)`,
	`CREATE INDEX IF NOT EXISTS ag_trajectory_entries_parent_idx
		ON ag_trajectory_entries (
			namespace,
			trajectory_id,
			parent_id
		)`,
	`CREATE INDEX IF NOT EXISTS ag_trajectory_entries_kind_idx
		ON ag_trajectory_entries (
			namespace,
			trajectory_id,
			kind,
			ordinal
		)`,
	`CREATE INDEX IF NOT EXISTS ag_trajectory_entries_execution_idx
		ON ag_trajectory_entries (namespace, execution_id, ordinal)`,
	`CREATE INDEX IF NOT EXISTS ag_trajectory_entries_operation_idx
		ON ag_trajectory_entries (namespace, operation_key)`,
	`CREATE INDEX IF NOT EXISTS ag_trajectory_entries_tool_idx
		ON ag_trajectory_entries (
			namespace,
			tool_name,
			tool_call_id
		)`,
	`CREATE INDEX IF NOT EXISTS ag_trajectory_entries_correlation_idx
		ON ag_trajectory_entries (namespace, correlation_id)`,
	`CREATE INDEX IF NOT EXISTS ag_trajectory_entries_time_idx
		ON ag_trajectory_entries (namespace, recorded_at)`,
	`CREATE INDEX IF NOT EXISTS ag_trajectory_executions_recovery_idx
		ON ag_trajectory_executions (
			namespace,
			state,
			lease_expires_at,
			created_at
		)`,
	`CREATE INDEX IF NOT EXISTS ag_operations_state_idx
		ON ag_operations (namespace, state, lease_expires_at, updated_at)`,
	`CREATE INDEX IF NOT EXISTS ag_operations_updated_idx
		ON ag_operations (namespace, updated_at, id)`,
	`CREATE INDEX IF NOT EXISTS ag_operations_invocation_root_idx
		ON ag_operations (namespace, ((invocation ->> 'root_id')))`,
	`CREATE INDEX IF NOT EXISTS ag_operations_invocation_parent_idx
		ON ag_operations (namespace, ((invocation ->> 'parent_id')))`,
	`CREATE INDEX IF NOT EXISTS ag_operations_invocation_group_idx
		ON ag_operations (namespace, ((invocation ->> 'group_id')))`,
	`CREATE INDEX IF NOT EXISTS ag_deliveries_ready_idx
		ON ag_deliveries (
			namespace,
			queue,
			state,
			available_at,
			lease_expires_at,
			sequence
		)`,
	`CREATE INDEX IF NOT EXISTS ag_deliveries_partition_idx
		ON ag_deliveries (
			namespace,
			queue,
			partition_key,
			sequence
		)`,
	`CREATE INDEX IF NOT EXISTS ag_deliveries_updated_idx
		ON ag_deliveries (namespace, updated_at, id)`,
}

func initPostgresStateSchema(
	ctx context.Context,
	pool *pgxpool.Pool,
) error {
	if _, err := postgresStateSchemaReady(ctx, pool); err != nil {
		return err
	}
	tx, err := pool.BeginTx(ctx, pgx.TxOptions{})
	if err != nil {
		return fmt.Errorf("begin PostgreSQL state schema transaction: %w", err)
	}
	defer func() { _ = tx.Rollback(context.Background()) }()
	if _, err := tx.Exec(
		ctx,
		`SELECT pg_advisory_xact_lock($1)`,
		postgresSchemaAdvisoryLock,
	); err != nil {
		return fmt.Errorf("lock PostgreSQL state schema: %w", err)
	}
	if _, err = postgresStateSchemaReady(ctx, tx); err != nil {
		return err
	}
	for _, statement := range postgresStateSchemaStatements {
		if _, err := tx.Exec(ctx, statement); err != nil {
			return fmt.Errorf("initialize PostgreSQL state schema: %w", err)
		}
	}
	var version int
	if err := tx.QueryRow(
		ctx,
		`SELECT version
		 FROM ag_storage_schema
		 WHERE component = 'state'`,
	).Scan(&version); err != nil {
		return fmt.Errorf("read PostgreSQL state schema version: %w", err)
	}
	if version != postgresStateSchemaVersion {
		return fmt.Errorf(
			"PostgreSQL state schema version %d is not supported; expected %d",
			version,
			postgresStateSchemaVersion,
		)
	}
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit PostgreSQL state schema: %w", err)
	}
	return nil
}

func postgresStateSchemaReady(
	ctx context.Context,
	query queryer,
) (bool, error) {
	var version int
	err := query.QueryRow(
		ctx,
		`SELECT version
		 FROM ag_storage_schema
		 WHERE component = 'state'`,
	).Scan(&version)
	if errors.Is(err, pgx.ErrNoRows) {
		return false, nil
	}
	var postgresError *pgconn.PgError
	if errors.As(err, &postgresError) &&
		postgresError.Code == "42P01" {
		return false, nil
	}
	if err != nil {
		return false, fmt.Errorf(
			"read PostgreSQL state schema version: %w",
			err,
		)
	}
	if version != postgresStateSchemaVersion {
		return false, fmt.Errorf(
			"PostgreSQL state schema version %d is not supported; expected %d",
			version,
			postgresStateSchemaVersion,
		)
	}
	return true, nil
}
