// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: gatewayrpc/v1/gateway.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_Health_FullMethodName                  = "/gatewayrpc.v1.GatewayService/Health"
	GatewayService_CreateTrajectory_FullMethodName        = "/gatewayrpc.v1.GatewayService/CreateTrajectory"
	GatewayService_GetTrajectory_FullMethodName           = "/gatewayrpc.v1.GatewayService/GetTrajectory"
	GatewayService_ListTrajectories_FullMethodName        = "/gatewayrpc.v1.GatewayService/ListTrajectories"
	GatewayService_LoadTrajectory_FullMethodName          = "/gatewayrpc.v1.GatewayService/LoadTrajectory"
	GatewayService_ListConversation_FullMethodName        = "/gatewayrpc.v1.GatewayService/ListConversation"
	GatewayService_ListTrajectoryEntries_FullMethodName   = "/gatewayrpc.v1.GatewayService/ListTrajectoryEntries"
	GatewayService_RollbackTrajectory_FullMethodName      = "/gatewayrpc.v1.GatewayService/RollbackTrajectory"
	GatewayService_AttachPlugin_FullMethodName            = "/gatewayrpc.v1.GatewayService/AttachPlugin"
	GatewayService_DetachPlugin_FullMethodName            = "/gatewayrpc.v1.GatewayService/DetachPlugin"
	GatewayService_SubmitMessage_FullMethodName           = "/gatewayrpc.v1.GatewayService/SubmitMessage"
	GatewayService_EnqueueContextInjection_FullMethodName = "/gatewayrpc.v1.GatewayService/EnqueueContextInjection"
	GatewayService_EnqueueInput_FullMethodName            = "/gatewayrpc.v1.GatewayService/EnqueueInput"
	GatewayService_GetInput_FullMethodName                = "/gatewayrpc.v1.GatewayService/GetInput"
	GatewayService_ListInputs_FullMethodName              = "/gatewayrpc.v1.GatewayService/ListInputs"
	GatewayService_CancelInput_FullMethodName             = "/gatewayrpc.v1.GatewayService/CancelInput"
	GatewayService_SetPaused_FullMethodName               = "/gatewayrpc.v1.GatewayService/SetPaused"
	GatewayService_ListEvents_FullMethodName              = "/gatewayrpc.v1.GatewayService/ListEvents"
	GatewayService_GetEventCursor_FullMethodName          = "/gatewayrpc.v1.GatewayService/GetEventCursor"
	GatewayService_GetInteraction_FullMethodName          = "/gatewayrpc.v1.GatewayService/GetInteraction"
	GatewayService_ListInteractions_FullMethodName        = "/gatewayrpc.v1.GatewayService/ListInteractions"
	GatewayService_ResolveInteraction_FullMethodName      = "/gatewayrpc.v1.GatewayService/ResolveInteraction"
	GatewayService_GetExecution_FullMethodName            = "/gatewayrpc.v1.GatewayService/GetExecution"
	GatewayService_CancelExecution_FullMethodName         = "/gatewayrpc.v1.GatewayService/CancelExecution"
	GatewayService_Connect_FullMethodName                 = "/gatewayrpc.v1.GatewayService/Connect"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GatewayService is the private control plane used by ag frontends. The
// public identity is a trajectory; the gateway's historical Session type is
// deliberately not part of this protocol's vocabulary.
type GatewayServiceClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	CreateTrajectory(ctx context.Context, in *CreateTrajectoryRequest, opts ...grpc.CallOption) (*JsonValue, error)
	GetTrajectory(ctx context.Context, in *GetTrajectoryRequest, opts ...grpc.CallOption) (*JsonValue, error)
	ListTrajectories(ctx context.Context, in *ListTrajectoriesRequest, opts ...grpc.CallOption) (*JsonValue, error)
	LoadTrajectory(ctx context.Context, in *LoadTrajectoryRequest, opts ...grpc.CallOption) (*JsonValue, error)
	ListConversation(ctx context.Context, in *ListConversationRequest, opts ...grpc.CallOption) (*JsonValue, error)
	ListTrajectoryEntries(ctx context.Context, in *ListTrajectoryEntriesRequest, opts ...grpc.CallOption) (*JsonValue, error)
	RollbackTrajectory(ctx context.Context, in *RollbackTrajectoryRequest, opts ...grpc.CallOption) (*JsonValue, error)
	AttachPlugin(ctx context.Context, in *AttachPluginRequest, opts ...grpc.CallOption) (*JsonValue, error)
	DetachPlugin(ctx context.Context, in *DetachPluginRequest, opts ...grpc.CallOption) (*JsonValue, error)
	SubmitMessage(ctx context.Context, in *SubmitMessageRequest, opts ...grpc.CallOption) (*JsonValue, error)
	EnqueueContextInjection(ctx context.Context, in *EnqueueContextInjectionRequest, opts ...grpc.CallOption) (*JsonValue, error)
	EnqueueInput(ctx context.Context, in *EnqueueInputRequest, opts ...grpc.CallOption) (*JsonValue, error)
	GetInput(ctx context.Context, in *GetInputRequest, opts ...grpc.CallOption) (*JsonValue, error)
	ListInputs(ctx context.Context, in *ListInputsRequest, opts ...grpc.CallOption) (*JsonValue, error)
	CancelInput(ctx context.Context, in *CancelInputRequest, opts ...grpc.CallOption) (*JsonValue, error)
	SetPaused(ctx context.Context, in *SetPausedRequest, opts ...grpc.CallOption) (*JsonValue, error)
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*JsonValue, error)
	GetEventCursor(ctx context.Context, in *GetEventCursorRequest, opts ...grpc.CallOption) (*JsonValue, error)
	GetInteraction(ctx context.Context, in *GetInteractionRequest, opts ...grpc.CallOption) (*JsonValue, error)
	ListInteractions(ctx context.Context, in *ListInteractionsRequest, opts ...grpc.CallOption) (*JsonValue, error)
	ResolveInteraction(ctx context.Context, in *ResolveInteractionRequest, opts ...grpc.CallOption) (*JsonValue, error)
	GetExecution(ctx context.Context, in *GetExecutionRequest, opts ...grpc.CallOption) (*JsonValue, error)
	CancelExecution(ctx context.Context, in *CancelExecutionRequest, opts ...grpc.CallOption) (*JsonValue, error)
	// Connect is one persistent, bidirectional attachment to a trajectory view.
	// The first client frame must be OpenView. Commands and durable events are
	// then multiplexed over the same HTTP/2 stream until the view detaches.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ViewRequest, ViewResponse], error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, GatewayService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) CreateTrajectory(ctx context.Context, in *CreateTrajectoryRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_CreateTrajectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetTrajectory(ctx context.Context, in *GetTrajectoryRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_GetTrajectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ListTrajectories(ctx context.Context, in *ListTrajectoriesRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_ListTrajectories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) LoadTrajectory(ctx context.Context, in *LoadTrajectoryRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_LoadTrajectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ListConversation(ctx context.Context, in *ListConversationRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_ListConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ListTrajectoryEntries(ctx context.Context, in *ListTrajectoryEntriesRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_ListTrajectoryEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) RollbackTrajectory(ctx context.Context, in *RollbackTrajectoryRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_RollbackTrajectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) AttachPlugin(ctx context.Context, in *AttachPluginRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_AttachPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) DetachPlugin(ctx context.Context, in *DetachPluginRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_DetachPlugin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) SubmitMessage(ctx context.Context, in *SubmitMessageRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_SubmitMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) EnqueueContextInjection(ctx context.Context, in *EnqueueContextInjectionRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_EnqueueContextInjection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) EnqueueInput(ctx context.Context, in *EnqueueInputRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_EnqueueInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetInput(ctx context.Context, in *GetInputRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_GetInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ListInputs(ctx context.Context, in *ListInputsRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_ListInputs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) CancelInput(ctx context.Context, in *CancelInputRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_CancelInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) SetPaused(ctx context.Context, in *SetPausedRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_SetPaused_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_ListEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetEventCursor(ctx context.Context, in *GetEventCursorRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_GetEventCursor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetInteraction(ctx context.Context, in *GetInteractionRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_GetInteraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ListInteractions(ctx context.Context, in *ListInteractionsRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_ListInteractions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ResolveInteraction(ctx context.Context, in *ResolveInteractionRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_ResolveInteraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetExecution(ctx context.Context, in *GetExecutionRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_GetExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) CancelExecution(ctx context.Context, in *CancelExecutionRequest, opts ...grpc.CallOption) (*JsonValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonValue)
	err := c.cc.Invoke(ctx, GatewayService_CancelExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ViewRequest, ViewResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayService_ServiceDesc.Streams[0], GatewayService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ViewRequest, ViewResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_ConnectClient = grpc.BidiStreamingClient[ViewRequest, ViewResponse]

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
//
// GatewayService is the private control plane used by ag frontends. The
// public identity is a trajectory; the gateway's historical Session type is
// deliberately not part of this protocol's vocabulary.
type GatewayServiceServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	CreateTrajectory(context.Context, *CreateTrajectoryRequest) (*JsonValue, error)
	GetTrajectory(context.Context, *GetTrajectoryRequest) (*JsonValue, error)
	ListTrajectories(context.Context, *ListTrajectoriesRequest) (*JsonValue, error)
	LoadTrajectory(context.Context, *LoadTrajectoryRequest) (*JsonValue, error)
	ListConversation(context.Context, *ListConversationRequest) (*JsonValue, error)
	ListTrajectoryEntries(context.Context, *ListTrajectoryEntriesRequest) (*JsonValue, error)
	RollbackTrajectory(context.Context, *RollbackTrajectoryRequest) (*JsonValue, error)
	AttachPlugin(context.Context, *AttachPluginRequest) (*JsonValue, error)
	DetachPlugin(context.Context, *DetachPluginRequest) (*JsonValue, error)
	SubmitMessage(context.Context, *SubmitMessageRequest) (*JsonValue, error)
	EnqueueContextInjection(context.Context, *EnqueueContextInjectionRequest) (*JsonValue, error)
	EnqueueInput(context.Context, *EnqueueInputRequest) (*JsonValue, error)
	GetInput(context.Context, *GetInputRequest) (*JsonValue, error)
	ListInputs(context.Context, *ListInputsRequest) (*JsonValue, error)
	CancelInput(context.Context, *CancelInputRequest) (*JsonValue, error)
	SetPaused(context.Context, *SetPausedRequest) (*JsonValue, error)
	ListEvents(context.Context, *ListEventsRequest) (*JsonValue, error)
	GetEventCursor(context.Context, *GetEventCursorRequest) (*JsonValue, error)
	GetInteraction(context.Context, *GetInteractionRequest) (*JsonValue, error)
	ListInteractions(context.Context, *ListInteractionsRequest) (*JsonValue, error)
	ResolveInteraction(context.Context, *ResolveInteractionRequest) (*JsonValue, error)
	GetExecution(context.Context, *GetExecutionRequest) (*JsonValue, error)
	CancelExecution(context.Context, *CancelExecutionRequest) (*JsonValue, error)
	// Connect is one persistent, bidirectional attachment to a trajectory view.
	// The first client frame must be OpenView. Commands and durable events are
	// then multiplexed over the same HTTP/2 stream until the view detaches.
	Connect(grpc.BidiStreamingServer[ViewRequest, ViewResponse]) error
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedGatewayServiceServer) CreateTrajectory(context.Context, *CreateTrajectoryRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTrajectory not implemented")
}
func (UnimplementedGatewayServiceServer) GetTrajectory(context.Context, *GetTrajectoryRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrajectory not implemented")
}
func (UnimplementedGatewayServiceServer) ListTrajectories(context.Context, *ListTrajectoriesRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrajectories not implemented")
}
func (UnimplementedGatewayServiceServer) LoadTrajectory(context.Context, *LoadTrajectoryRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadTrajectory not implemented")
}
func (UnimplementedGatewayServiceServer) ListConversation(context.Context, *ListConversationRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConversation not implemented")
}
func (UnimplementedGatewayServiceServer) ListTrajectoryEntries(context.Context, *ListTrajectoryEntriesRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrajectoryEntries not implemented")
}
func (UnimplementedGatewayServiceServer) RollbackTrajectory(context.Context, *RollbackTrajectoryRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackTrajectory not implemented")
}
func (UnimplementedGatewayServiceServer) AttachPlugin(context.Context, *AttachPluginRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachPlugin not implemented")
}
func (UnimplementedGatewayServiceServer) DetachPlugin(context.Context, *DetachPluginRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method DetachPlugin not implemented")
}
func (UnimplementedGatewayServiceServer) SubmitMessage(context.Context, *SubmitMessageRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitMessage not implemented")
}
func (UnimplementedGatewayServiceServer) EnqueueContextInjection(context.Context, *EnqueueContextInjectionRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueContextInjection not implemented")
}
func (UnimplementedGatewayServiceServer) EnqueueInput(context.Context, *EnqueueInputRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueInput not implemented")
}
func (UnimplementedGatewayServiceServer) GetInput(context.Context, *GetInputRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInput not implemented")
}
func (UnimplementedGatewayServiceServer) ListInputs(context.Context, *ListInputsRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInputs not implemented")
}
func (UnimplementedGatewayServiceServer) CancelInput(context.Context, *CancelInputRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelInput not implemented")
}
func (UnimplementedGatewayServiceServer) SetPaused(context.Context, *SetPausedRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPaused not implemented")
}
func (UnimplementedGatewayServiceServer) ListEvents(context.Context, *ListEventsRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedGatewayServiceServer) GetEventCursor(context.Context, *GetEventCursorRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventCursor not implemented")
}
func (UnimplementedGatewayServiceServer) GetInteraction(context.Context, *GetInteractionRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInteraction not implemented")
}
func (UnimplementedGatewayServiceServer) ListInteractions(context.Context, *ListInteractionsRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInteractions not implemented")
}
func (UnimplementedGatewayServiceServer) ResolveInteraction(context.Context, *ResolveInteractionRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveInteraction not implemented")
}
func (UnimplementedGatewayServiceServer) GetExecution(context.Context, *GetExecutionRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExecution not implemented")
}
func (UnimplementedGatewayServiceServer) CancelExecution(context.Context, *CancelExecutionRequest) (*JsonValue, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelExecution not implemented")
}
func (UnimplementedGatewayServiceServer) Connect(grpc.BidiStreamingServer[ViewRequest, ViewResponse]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_CreateTrajectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTrajectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).CreateTrajectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_CreateTrajectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).CreateTrajectory(ctx, req.(*CreateTrajectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetTrajectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrajectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetTrajectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetTrajectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetTrajectory(ctx, req.(*GetTrajectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ListTrajectories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrajectoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListTrajectories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListTrajectories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListTrajectories(ctx, req.(*ListTrajectoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_LoadTrajectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadTrajectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).LoadTrajectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_LoadTrajectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).LoadTrajectory(ctx, req.(*LoadTrajectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ListConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListConversation(ctx, req.(*ListConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ListTrajectoryEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrajectoryEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListTrajectoryEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListTrajectoryEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListTrajectoryEntries(ctx, req.(*ListTrajectoryEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_RollbackTrajectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackTrajectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).RollbackTrajectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_RollbackTrajectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).RollbackTrajectory(ctx, req.(*RollbackTrajectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_AttachPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).AttachPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_AttachPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).AttachPlugin(ctx, req.(*AttachPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_DetachPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).DetachPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_DetachPlugin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).DetachPlugin(ctx, req.(*DetachPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_SubmitMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).SubmitMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_SubmitMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).SubmitMessage(ctx, req.(*SubmitMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_EnqueueContextInjection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueContextInjectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).EnqueueContextInjection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_EnqueueContextInjection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).EnqueueContextInjection(ctx, req.(*EnqueueContextInjectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_EnqueueInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).EnqueueInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_EnqueueInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).EnqueueInput(ctx, req.(*EnqueueInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetInput(ctx, req.(*GetInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ListInputs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInputsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListInputs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListInputs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListInputs(ctx, req.(*ListInputsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_CancelInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).CancelInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_CancelInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).CancelInput(ctx, req.(*CancelInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_SetPaused_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPausedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).SetPaused(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_SetPaused_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).SetPaused(ctx, req.(*SetPausedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetEventCursor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventCursorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetEventCursor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetEventCursor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetEventCursor(ctx, req.(*GetEventCursorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetInteraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetInteraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetInteraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetInteraction(ctx, req.(*GetInteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ListInteractions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInteractionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListInteractions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListInteractions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListInteractions(ctx, req.(*ListInteractionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ResolveInteraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveInteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ResolveInteraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ResolveInteraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ResolveInteraction(ctx, req.(*ResolveInteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetExecution(ctx, req.(*GetExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_CancelExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).CancelExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_CancelExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).CancelExecution(ctx, req.(*CancelExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayServiceServer).Connect(&grpc.GenericServerStream[ViewRequest, ViewResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_ConnectServer = grpc.BidiStreamingServer[ViewRequest, ViewResponse]

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gatewayrpc.v1.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _GatewayService_Health_Handler,
		},
		{
			MethodName: "CreateTrajectory",
			Handler:    _GatewayService_CreateTrajectory_Handler,
		},
		{
			MethodName: "GetTrajectory",
			Handler:    _GatewayService_GetTrajectory_Handler,
		},
		{
			MethodName: "ListTrajectories",
			Handler:    _GatewayService_ListTrajectories_Handler,
		},
		{
			MethodName: "LoadTrajectory",
			Handler:    _GatewayService_LoadTrajectory_Handler,
		},
		{
			MethodName: "ListConversation",
			Handler:    _GatewayService_ListConversation_Handler,
		},
		{
			MethodName: "ListTrajectoryEntries",
			Handler:    _GatewayService_ListTrajectoryEntries_Handler,
		},
		{
			MethodName: "RollbackTrajectory",
			Handler:    _GatewayService_RollbackTrajectory_Handler,
		},
		{
			MethodName: "AttachPlugin",
			Handler:    _GatewayService_AttachPlugin_Handler,
		},
		{
			MethodName: "DetachPlugin",
			Handler:    _GatewayService_DetachPlugin_Handler,
		},
		{
			MethodName: "SubmitMessage",
			Handler:    _GatewayService_SubmitMessage_Handler,
		},
		{
			MethodName: "EnqueueContextInjection",
			Handler:    _GatewayService_EnqueueContextInjection_Handler,
		},
		{
			MethodName: "EnqueueInput",
			Handler:    _GatewayService_EnqueueInput_Handler,
		},
		{
			MethodName: "GetInput",
			Handler:    _GatewayService_GetInput_Handler,
		},
		{
			MethodName: "ListInputs",
			Handler:    _GatewayService_ListInputs_Handler,
		},
		{
			MethodName: "CancelInput",
			Handler:    _GatewayService_CancelInput_Handler,
		},
		{
			MethodName: "SetPaused",
			Handler:    _GatewayService_SetPaused_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _GatewayService_ListEvents_Handler,
		},
		{
			MethodName: "GetEventCursor",
			Handler:    _GatewayService_GetEventCursor_Handler,
		},
		{
			MethodName: "GetInteraction",
			Handler:    _GatewayService_GetInteraction_Handler,
		},
		{
			MethodName: "ListInteractions",
			Handler:    _GatewayService_ListInteractions_Handler,
		},
		{
			MethodName: "ResolveInteraction",
			Handler:    _GatewayService_ResolveInteraction_Handler,
		},
		{
			MethodName: "GetExecution",
			Handler:    _GatewayService_GetExecution_Handler,
		},
		{
			MethodName: "CancelExecution",
			Handler:    _GatewayService_CancelExecution_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _GatewayService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gatewayrpc/v1/gateway.proto",
}
