// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gatewayrpc/v1/gateway.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

// JsonValue keeps the RPC operation contract typed while allowing the gateway
// domain model to evolve without maintaining a second copy of every runtime
// structure in protobuf. The payload is one canonical JSON value.
type JsonValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonValue) Reset() {
	*x = JsonValue{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonValue) ProtoMessage() {}

func (x *JsonValue) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonValue.ProtoReflect.Descriptor instead.
func (*JsonValue) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *JsonValue) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

type CreateTrajectoryRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id                string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Provider          string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	System            string                 `protobuf:"bytes,4,opt,name=system,proto3" json:"system,omitempty"`
	MaxTurns          int32                  `protobuf:"varint,5,opt,name=max_turns,json=maxTurns,proto3" json:"max_turns,omitempty"`
	WorkspaceRoot     string                 `protobuf:"bytes,6,opt,name=workspace_root,json=workspaceRoot,proto3" json:"workspace_root,omitempty"`
	RuntimeConfigJson []byte                 `protobuf:"bytes,7,opt,name=runtime_config_json,json=runtimeConfigJson,proto3" json:"runtime_config_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateTrajectoryRequest) Reset() {
	*x = CreateTrajectoryRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTrajectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTrajectoryRequest) ProtoMessage() {}

func (x *CreateTrajectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTrajectoryRequest.ProtoReflect.Descriptor instead.
func (*CreateTrajectoryRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTrajectoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTrajectoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTrajectoryRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreateTrajectoryRequest) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *CreateTrajectoryRequest) GetMaxTurns() int32 {
	if x != nil {
		return x.MaxTurns
	}
	return 0
}

func (x *CreateTrajectoryRequest) GetWorkspaceRoot() string {
	if x != nil {
		return x.WorkspaceRoot
	}
	return ""
}

func (x *CreateTrajectoryRequest) GetRuntimeConfigJson() []byte {
	if x != nil {
		return x.RuntimeConfigJson
	}
	return nil
}

type GetTrajectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId  string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrajectoryRequest) Reset() {
	*x = GetTrajectoryRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrajectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrajectoryRequest) ProtoMessage() {}

func (x *GetTrajectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrajectoryRequest.ProtoReflect.Descriptor instead.
func (*GetTrajectoryRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *GetTrajectoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTrajectoryRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

type ListTrajectoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	After         string                 `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrajectoriesRequest) Reset() {
	*x = ListTrajectoriesRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrajectoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrajectoriesRequest) ProtoMessage() {}

func (x *ListTrajectoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrajectoriesRequest.ProtoReflect.Descriptor instead.
func (*ListTrajectoriesRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *ListTrajectoriesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListTrajectoriesRequest) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *ListTrajectoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LoadTrajectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId  string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	Head          string                 `protobuf:"bytes,3,opt,name=head,proto3" json:"head,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadTrajectoryRequest) Reset() {
	*x = LoadTrajectoryRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadTrajectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadTrajectoryRequest) ProtoMessage() {}

func (x *LoadTrajectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadTrajectoryRequest.ProtoReflect.Descriptor instead.
func (*LoadTrajectoryRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *LoadTrajectoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoadTrajectoryRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *LoadTrajectoryRequest) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

type ListConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId  string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	Head          string                 `protobuf:"bytes,3,opt,name=head,proto3" json:"head,omitempty"`
	After         uint64                 `protobuf:"varint,4,opt,name=after,proto3" json:"after,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationRequest) Reset() {
	*x = ListConversationRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationRequest) ProtoMessage() {}

func (x *ListConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationRequest.ProtoReflect.Descriptor instead.
func (*ListConversationRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *ListConversationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListConversationRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *ListConversationRequest) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

func (x *ListConversationRequest) GetAfter() uint64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *ListConversationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListTrajectoryEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId  string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	Head          string                 `protobuf:"bytes,3,opt,name=head,proto3" json:"head,omitempty"`
	After         uint64                 `protobuf:"varint,4,opt,name=after,proto3" json:"after,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrajectoryEntriesRequest) Reset() {
	*x = ListTrajectoryEntriesRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrajectoryEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrajectoryEntriesRequest) ProtoMessage() {}

func (x *ListTrajectoryEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrajectoryEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListTrajectoryEntriesRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *ListTrajectoryEntriesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListTrajectoryEntriesRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *ListTrajectoryEntriesRequest) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

func (x *ListTrajectoryEntriesRequest) GetAfter() uint64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *ListTrajectoryEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RollbackTrajectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId  string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	CheckpointId  string                 `protobuf:"bytes,3,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackTrajectoryRequest) Reset() {
	*x = RollbackTrajectoryRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackTrajectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackTrajectoryRequest) ProtoMessage() {}

func (x *RollbackTrajectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackTrajectoryRequest.ProtoReflect.Descriptor instead.
func (*RollbackTrajectoryRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *RollbackTrajectoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RollbackTrajectoryRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *RollbackTrajectoryRequest) GetCheckpointId() string {
	if x != nil {
		return x.CheckpointId
	}
	return ""
}

type AttachPluginRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId     string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	Selector         string                 `protobuf:"bytes,3,opt,name=selector,proto3" json:"selector,omitempty"`
	ExpectedRevision uint64                 `protobuf:"varint,4,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AttachPluginRequest) Reset() {
	*x = AttachPluginRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachPluginRequest) ProtoMessage() {}

func (x *AttachPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachPluginRequest.ProtoReflect.Descriptor instead.
func (*AttachPluginRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *AttachPluginRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AttachPluginRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *AttachPluginRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *AttachPluginRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type DetachPluginRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId     string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ExpectedRevision uint64                 `protobuf:"varint,4,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DetachPluginRequest) Reset() {
	*x = DetachPluginRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachPluginRequest) ProtoMessage() {}

func (x *DetachPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachPluginRequest.ProtoReflect.Descriptor instead.
func (*DetachPluginRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *DetachPluginRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DetachPluginRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *DetachPluginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DetachPluginRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type SubmitMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId  string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitMessageRequest) Reset() {
	*x = SubmitMessageRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMessageRequest) ProtoMessage() {}

func (x *SubmitMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMessageRequest.ProtoReflect.Descriptor instead.
func (*SubmitMessageRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubmitMessageRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *SubmitMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type EnqueueContextInjectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId  string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	InjectionJson []byte                 `protobuf:"bytes,4,opt,name=injection_json,json=injectionJson,proto3" json:"injection_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueContextInjectionRequest) Reset() {
	*x = EnqueueContextInjectionRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueContextInjectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueContextInjectionRequest) ProtoMessage() {}

func (x *EnqueueContextInjectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueContextInjectionRequest.ProtoReflect.Descriptor instead.
func (*EnqueueContextInjectionRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *EnqueueContextInjectionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EnqueueContextInjectionRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *EnqueueContextInjectionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *EnqueueContextInjectionRequest) GetInjectionJson() []byte {
	if x != nil {
		return x.InjectionJson
	}
	return nil
}

type EnqueueInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId  string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	InputId       string                 `protobuf:"bytes,3,opt,name=input_id,json=inputId,proto3" json:"input_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueInputRequest) Reset() {
	*x = EnqueueInputRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueInputRequest) ProtoMessage() {}

func (x *EnqueueInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueInputRequest.ProtoReflect.Descriptor instead.
func (*EnqueueInputRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *EnqueueInputRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EnqueueInputRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *EnqueueInputRequest) GetInputId() string {
	if x != nil {
		return x.InputId
	}
	return ""
}

func (x *EnqueueInputRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId  string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	InputId       string                 `protobuf:"bytes,3,opt,name=input_id,json=inputId,proto3" json:"input_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInputRequest) Reset() {
	*x = GetInputRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInputRequest) ProtoMessage() {}

func (x *GetInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInputRequest.ProtoReflect.Descriptor instead.
func (*GetInputRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *GetInputRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetInputRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *GetInputRequest) GetInputId() string {
	if x != nil {
		return x.InputId
	}
	return ""
}

type ListInputsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId  string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	After         uint64                 `protobuf:"varint,3,opt,name=after,proto3" json:"after,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInputsRequest) Reset() {
	*x = ListInputsRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInputsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInputsRequest) ProtoMessage() {}

func (x *ListInputsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInputsRequest.ProtoReflect.Descriptor instead.
func (*ListInputsRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{16}
}

func (x *ListInputsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListInputsRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *ListInputsRequest) GetAfter() uint64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *ListInputsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CancelInputRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId     string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	InputId          string                 `protobuf:"bytes,3,opt,name=input_id,json=inputId,proto3" json:"input_id,omitempty"`
	ExpectedRevision uint64                 `protobuf:"varint,4,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CancelInputRequest) Reset() {
	*x = CancelInputRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelInputRequest) ProtoMessage() {}

func (x *CancelInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelInputRequest.ProtoReflect.Descriptor instead.
func (*CancelInputRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{17}
}

func (x *CancelInputRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CancelInputRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *CancelInputRequest) GetInputId() string {
	if x != nil {
		return x.InputId
	}
	return ""
}

func (x *CancelInputRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type SetPausedRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId     string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	Paused           bool                   `protobuf:"varint,3,opt,name=paused,proto3" json:"paused,omitempty"`
	ExpectedRevision uint64                 `protobuf:"varint,4,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetPausedRequest) Reset() {
	*x = SetPausedRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPausedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPausedRequest) ProtoMessage() {}

func (x *SetPausedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPausedRequest.ProtoReflect.Descriptor instead.
func (*SetPausedRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{18}
}

func (x *SetPausedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetPausedRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *SetPausedRequest) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *SetPausedRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId  string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	After         uint64                 `protobuf:"varint,3,opt,name=after,proto3" json:"after,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{19}
}

func (x *ListEventsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListEventsRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *ListEventsRequest) GetAfter() uint64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *ListEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetEventCursorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId  string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventCursorRequest) Reset() {
	*x = GetEventCursorRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventCursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventCursorRequest) ProtoMessage() {}

func (x *GetEventCursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventCursorRequest.ProtoReflect.Descriptor instead.
func (*GetEventCursorRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{20}
}

func (x *GetEventCursorRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetEventCursorRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

type GetInteractionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId  string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	InteractionId string                 `protobuf:"bytes,3,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInteractionRequest) Reset() {
	*x = GetInteractionRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInteractionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInteractionRequest) ProtoMessage() {}

func (x *GetInteractionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInteractionRequest.ProtoReflect.Descriptor instead.
func (*GetInteractionRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{21}
}

func (x *GetInteractionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetInteractionRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *GetInteractionRequest) GetInteractionId() string {
	if x != nil {
		return x.InteractionId
	}
	return ""
}

type ListInteractionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId  string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	After         uint64                 `protobuf:"varint,3,opt,name=after,proto3" json:"after,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInteractionsRequest) Reset() {
	*x = ListInteractionsRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInteractionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInteractionsRequest) ProtoMessage() {}

func (x *ListInteractionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInteractionsRequest.ProtoReflect.Descriptor instead.
func (*ListInteractionsRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{22}
}

func (x *ListInteractionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListInteractionsRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *ListInteractionsRequest) GetAfter() uint64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *ListInteractionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListInteractionsRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ResolveInteractionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId     string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	InteractionId    string                 `protobuf:"bytes,3,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	ExpectedRevision uint64                 `protobuf:"varint,4,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	OptionId         string                 `protobuf:"bytes,5,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
	Text             string                 `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResolveInteractionRequest) Reset() {
	*x = ResolveInteractionRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveInteractionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveInteractionRequest) ProtoMessage() {}

func (x *ResolveInteractionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveInteractionRequest.ProtoReflect.Descriptor instead.
func (*ResolveInteractionRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{23}
}

func (x *ResolveInteractionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResolveInteractionRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *ResolveInteractionRequest) GetInteractionId() string {
	if x != nil {
		return x.InteractionId
	}
	return ""
}

func (x *ResolveInteractionRequest) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *ResolveInteractionRequest) GetOptionId() string {
	if x != nil {
		return x.OptionId
	}
	return ""
}

func (x *ResolveInteractionRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId  string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionRequest) Reset() {
	*x = GetExecutionRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionRequest) ProtoMessage() {}

func (x *GetExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{24}
}

func (x *GetExecutionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetExecutionRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *GetExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type CancelExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId  string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelExecutionRequest) Reset() {
	*x = CancelExecutionRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExecutionRequest) ProtoMessage() {}

func (x *CancelExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExecutionRequest.ProtoReflect.Descriptor instead.
func (*CancelExecutionRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{25}
}

func (x *CancelExecutionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CancelExecutionRequest) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *CancelExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type ViewRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ViewRequest_Open
	//	*ViewRequest_Command
	Frame         isViewRequest_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewRequest) Reset() {
	*x = ViewRequest{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewRequest) ProtoMessage() {}

func (x *ViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewRequest.ProtoReflect.Descriptor instead.
func (*ViewRequest) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{26}
}

func (x *ViewRequest) GetFrame() isViewRequest_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ViewRequest) GetOpen() *OpenView {
	if x != nil {
		if x, ok := x.Frame.(*ViewRequest_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *ViewRequest) GetCommand() *ViewCommand {
	if x != nil {
		if x, ok := x.Frame.(*ViewRequest_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isViewRequest_Frame interface {
	isViewRequest_Frame()
}

type ViewRequest_Open struct {
	Open *OpenView `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type ViewRequest_Command struct {
	Command *ViewCommand `protobuf:"bytes,2,opt,name=command,proto3,oneof"`
}

func (*ViewRequest_Open) isViewRequest_Frame() {}

func (*ViewRequest_Command) isViewRequest_Frame() {}

type OpenView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TrajectoryId  string                 `protobuf:"bytes,2,opt,name=trajectory_id,json=trajectoryId,proto3" json:"trajectory_id,omitempty"`
	AfterEvent    uint64                 `protobuf:"varint,3,opt,name=after_event,json=afterEvent,proto3" json:"after_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenView) Reset() {
	*x = OpenView{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenView) ProtoMessage() {}

func (x *OpenView) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenView.ProtoReflect.Descriptor instead.
func (*OpenView) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{27}
}

func (x *OpenView) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OpenView) GetTrajectoryId() string {
	if x != nil {
		return x.TrajectoryId
	}
	return ""
}

func (x *OpenView) GetAfterEvent() uint64 {
	if x != nil {
		return x.AfterEvent
	}
	return 0
}

type ViewCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*ViewCommand_EnqueueInput
	//	*ViewCommand_CancelInput
	//	*ViewCommand_ResolveInteraction
	//	*ViewCommand_SetPaused
	//	*ViewCommand_CancelExecution
	Command       isViewCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewCommand) Reset() {
	*x = ViewCommand{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewCommand) ProtoMessage() {}

func (x *ViewCommand) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewCommand.ProtoReflect.Descriptor instead.
func (*ViewCommand) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{28}
}

func (x *ViewCommand) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ViewCommand) GetCommand() isViewCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ViewCommand) GetEnqueueInput() *ViewEnqueueInput {
	if x != nil {
		if x, ok := x.Command.(*ViewCommand_EnqueueInput); ok {
			return x.EnqueueInput
		}
	}
	return nil
}

func (x *ViewCommand) GetCancelInput() *ViewCancelInput {
	if x != nil {
		if x, ok := x.Command.(*ViewCommand_CancelInput); ok {
			return x.CancelInput
		}
	}
	return nil
}

func (x *ViewCommand) GetResolveInteraction() *ViewResolveInteraction {
	if x != nil {
		if x, ok := x.Command.(*ViewCommand_ResolveInteraction); ok {
			return x.ResolveInteraction
		}
	}
	return nil
}

func (x *ViewCommand) GetSetPaused() *ViewSetPaused {
	if x != nil {
		if x, ok := x.Command.(*ViewCommand_SetPaused); ok {
			return x.SetPaused
		}
	}
	return nil
}

func (x *ViewCommand) GetCancelExecution() *ViewCancelExecution {
	if x != nil {
		if x, ok := x.Command.(*ViewCommand_CancelExecution); ok {
			return x.CancelExecution
		}
	}
	return nil
}

type isViewCommand_Command interface {
	isViewCommand_Command()
}

type ViewCommand_EnqueueInput struct {
	EnqueueInput *ViewEnqueueInput `protobuf:"bytes,2,opt,name=enqueue_input,json=enqueueInput,proto3,oneof"`
}

type ViewCommand_CancelInput struct {
	CancelInput *ViewCancelInput `protobuf:"bytes,3,opt,name=cancel_input,json=cancelInput,proto3,oneof"`
}

type ViewCommand_ResolveInteraction struct {
	ResolveInteraction *ViewResolveInteraction `protobuf:"bytes,4,opt,name=resolve_interaction,json=resolveInteraction,proto3,oneof"`
}

type ViewCommand_SetPaused struct {
	SetPaused *ViewSetPaused `protobuf:"bytes,5,opt,name=set_paused,json=setPaused,proto3,oneof"`
}

type ViewCommand_CancelExecution struct {
	CancelExecution *ViewCancelExecution `protobuf:"bytes,6,opt,name=cancel_execution,json=cancelExecution,proto3,oneof"`
}

func (*ViewCommand_EnqueueInput) isViewCommand_Command() {}

func (*ViewCommand_CancelInput) isViewCommand_Command() {}

func (*ViewCommand_ResolveInteraction) isViewCommand_Command() {}

func (*ViewCommand_SetPaused) isViewCommand_Command() {}

func (*ViewCommand_CancelExecution) isViewCommand_Command() {}

type ViewEnqueueInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputId       string                 `protobuf:"bytes,1,opt,name=input_id,json=inputId,proto3" json:"input_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewEnqueueInput) Reset() {
	*x = ViewEnqueueInput{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewEnqueueInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewEnqueueInput) ProtoMessage() {}

func (x *ViewEnqueueInput) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewEnqueueInput.ProtoReflect.Descriptor instead.
func (*ViewEnqueueInput) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{29}
}

func (x *ViewEnqueueInput) GetInputId() string {
	if x != nil {
		return x.InputId
	}
	return ""
}

func (x *ViewEnqueueInput) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ViewCancelInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InputId          string                 `protobuf:"bytes,1,opt,name=input_id,json=inputId,proto3" json:"input_id,omitempty"`
	ExpectedRevision uint64                 `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ViewCancelInput) Reset() {
	*x = ViewCancelInput{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewCancelInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewCancelInput) ProtoMessage() {}

func (x *ViewCancelInput) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewCancelInput.ProtoReflect.Descriptor instead.
func (*ViewCancelInput) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{30}
}

func (x *ViewCancelInput) GetInputId() string {
	if x != nil {
		return x.InputId
	}
	return ""
}

func (x *ViewCancelInput) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type ViewResolveInteraction struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InteractionId    string                 `protobuf:"bytes,1,opt,name=interaction_id,json=interactionId,proto3" json:"interaction_id,omitempty"`
	ExpectedRevision uint64                 `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	OptionId         string                 `protobuf:"bytes,3,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
	Text             string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ViewResolveInteraction) Reset() {
	*x = ViewResolveInteraction{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewResolveInteraction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewResolveInteraction) ProtoMessage() {}

func (x *ViewResolveInteraction) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewResolveInteraction.ProtoReflect.Descriptor instead.
func (*ViewResolveInteraction) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{31}
}

func (x *ViewResolveInteraction) GetInteractionId() string {
	if x != nil {
		return x.InteractionId
	}
	return ""
}

func (x *ViewResolveInteraction) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *ViewResolveInteraction) GetOptionId() string {
	if x != nil {
		return x.OptionId
	}
	return ""
}

func (x *ViewResolveInteraction) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ViewSetPaused struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Paused           bool                   `protobuf:"varint,1,opt,name=paused,proto3" json:"paused,omitempty"`
	ExpectedRevision uint64                 `protobuf:"varint,2,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ViewSetPaused) Reset() {
	*x = ViewSetPaused{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewSetPaused) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewSetPaused) ProtoMessage() {}

func (x *ViewSetPaused) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewSetPaused.ProtoReflect.Descriptor instead.
func (*ViewSetPaused) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{32}
}

func (x *ViewSetPaused) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *ViewSetPaused) GetExpectedRevision() uint64 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type ViewCancelExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewCancelExecution) Reset() {
	*x = ViewCancelExecution{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewCancelExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewCancelExecution) ProtoMessage() {}

func (x *ViewCancelExecution) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewCancelExecution.ProtoReflect.Descriptor instead.
func (*ViewCancelExecution) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{33}
}

func (x *ViewCancelExecution) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type ViewResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ViewResponse_Ready
	//	*ViewResponse_Event
	//	*ViewResponse_Result
	//	*ViewResponse_Failure
	Frame         isViewResponse_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewResponse) Reset() {
	*x = ViewResponse{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewResponse) ProtoMessage() {}

func (x *ViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewResponse.ProtoReflect.Descriptor instead.
func (*ViewResponse) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{34}
}

func (x *ViewResponse) GetFrame() isViewResponse_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ViewResponse) GetReady() *ViewReady {
	if x != nil {
		if x, ok := x.Frame.(*ViewResponse_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *ViewResponse) GetEvent() *ViewEvent {
	if x != nil {
		if x, ok := x.Frame.(*ViewResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *ViewResponse) GetResult() *ViewResult {
	if x != nil {
		if x, ok := x.Frame.(*ViewResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ViewResponse) GetFailure() *ViewFailure {
	if x != nil {
		if x, ok := x.Frame.(*ViewResponse_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isViewResponse_Frame interface {
	isViewResponse_Frame()
}

type ViewResponse_Ready struct {
	Ready *ViewReady `protobuf:"bytes,1,opt,name=ready,proto3,oneof"`
}

type ViewResponse_Event struct {
	Event *ViewEvent `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

type ViewResponse_Result struct {
	Result *ViewResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

type ViewResponse_Failure struct {
	Failure *ViewFailure `protobuf:"bytes,4,opt,name=failure,proto3,oneof"`
}

func (*ViewResponse_Ready) isViewResponse_Frame() {}

func (*ViewResponse_Event) isViewResponse_Frame() {}

func (*ViewResponse_Result) isViewResponse_Frame() {}

func (*ViewResponse_Failure) isViewResponse_Frame() {}

type ViewReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trajectory    *JsonValue             `protobuf:"bytes,1,opt,name=trajectory,proto3" json:"trajectory,omitempty"`
	Cursor        uint64                 `protobuf:"varint,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewReady) Reset() {
	*x = ViewReady{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewReady) ProtoMessage() {}

func (x *ViewReady) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewReady.ProtoReflect.Descriptor instead.
func (*ViewReady) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{35}
}

func (x *ViewReady) GetTrajectory() *JsonValue {
	if x != nil {
		return x.Trajectory
	}
	return nil
}

func (x *ViewReady) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

type ViewEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *JsonValue             `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewEvent) Reset() {
	*x = ViewEvent{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewEvent) ProtoMessage() {}

func (x *ViewEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewEvent.ProtoReflect.Descriptor instead.
func (*ViewEvent) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{36}
}

func (x *ViewEvent) GetEvent() *JsonValue {
	if x != nil {
		return x.Event
	}
	return nil
}

type ViewResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Value         *JsonValue             `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewResult) Reset() {
	*x = ViewResult{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewResult) ProtoMessage() {}

func (x *ViewResult) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewResult.ProtoReflect.Descriptor instead.
func (*ViewResult) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{37}
}

func (x *ViewResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ViewResult) GetValue() *JsonValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type ViewFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewFailure) Reset() {
	*x = ViewFailure{}
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewFailure) ProtoMessage() {}

func (x *ViewFailure) ProtoReflect() protoreflect.Message {
	mi := &file_gatewayrpc_v1_gateway_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewFailure.ProtoReflect.Descriptor instead.
func (*ViewFailure) Descriptor() ([]byte, []int) {
	return file_gatewayrpc_v1_gateway_proto_rawDescGZIP(), []int{38}
}

func (x *ViewFailure) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ViewFailure) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ViewFailure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_gatewayrpc_v1_gateway_proto protoreflect.FileDescriptor

const file_gatewayrpc_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1bgatewayrpc/v1/gateway.proto\x12\rgatewayrpc.v1\"\x0f\n" +
	"\rHealthRequest\"S\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\"\x1f\n" +
	"\tJsonValue\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\"\xea\x01\n" +
	"\x17CreateTrajectoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x16\n" +
	"\x06system\x18\x04 \x01(\tR\x06system\x12\x1b\n" +
	"\tmax_turns\x18\x05 \x01(\x05R\bmaxTurns\x12%\n" +
	"\x0eworkspace_root\x18\x06 \x01(\tR\rworkspaceRoot\x12.\n" +
	"\x13runtime_config_json\x18\a \x01(\fR\x11runtimeConfigJson\"T\n" +
	"\x14GetTrajectoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\"^\n" +
	"\x17ListTrajectoriesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05after\x18\x02 \x01(\tR\x05after\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"i\n" +
	"\x15LoadTrajectoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\x12\x12\n" +
	"\x04head\x18\x03 \x01(\tR\x04head\"\x97\x01\n" +
	"\x17ListConversationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\x12\x12\n" +
	"\x04head\x18\x03 \x01(\tR\x04head\x12\x14\n" +
	"\x05after\x18\x04 \x01(\x04R\x05after\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\x9c\x01\n" +
	"\x1cListTrajectoryEntriesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\x12\x12\n" +
	"\x04head\x18\x03 \x01(\tR\x04head\x12\x14\n" +
	"\x05after\x18\x04 \x01(\x04R\x05after\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"~\n" +
	"\x19RollbackTrajectoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\x12#\n" +
	"\rcheckpoint_id\x18\x03 \x01(\tR\fcheckpointId\"\x9c\x01\n" +
	"\x13AttachPluginRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\x12\x1a\n" +
	"\bselector\x18\x03 \x01(\tR\bselector\x12+\n" +
	"\x11expected_revision\x18\x04 \x01(\x04R\x10expectedRevision\"\x94\x01\n" +
	"\x13DetachPluginRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12+\n" +
	"\x11expected_revision\x18\x04 \x01(\x04R\x10expectedRevision\"n\n" +
	"\x14SubmitMessageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\xa8\x01\n" +
	"\x1eEnqueueContextInjectionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\x12!\n" +
	"\fexecution_id\x18\x03 \x01(\tR\vexecutionId\x12%\n" +
	"\x0einjection_json\x18\x04 \x01(\fR\rinjectionJson\"\x88\x01\n" +
	"\x13EnqueueInputRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\x12\x19\n" +
	"\binput_id\x18\x03 \x01(\tR\ainputId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"j\n" +
	"\x0fGetInputRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\x12\x19\n" +
	"\binput_id\x18\x03 \x01(\tR\ainputId\"}\n" +
	"\x11ListInputsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\x12\x14\n" +
	"\x05after\x18\x03 \x01(\x04R\x05after\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x9a\x01\n" +
	"\x12CancelInputRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\x12\x19\n" +
	"\binput_id\x18\x03 \x01(\tR\ainputId\x12+\n" +
	"\x11expected_revision\x18\x04 \x01(\x04R\x10expectedRevision\"\x95\x01\n" +
	"\x10SetPausedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\x12\x16\n" +
	"\x06paused\x18\x03 \x01(\bR\x06paused\x12+\n" +
	"\x11expected_revision\x18\x04 \x01(\x04R\x10expectedRevision\"}\n" +
	"\x11ListEventsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\x12\x14\n" +
	"\x05after\x18\x03 \x01(\x04R\x05after\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"U\n" +
	"\x15GetEventCursorRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\"|\n" +
	"\x15GetInteractionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\x12%\n" +
	"\x0einteraction_id\x18\x03 \x01(\tR\rinteractionId\"\x99\x01\n" +
	"\x17ListInteractionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\x12\x14\n" +
	"\x05after\x18\x03 \x01(\x04R\x05after\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\"\xde\x01\n" +
	"\x19ResolveInteractionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\x12%\n" +
	"\x0einteraction_id\x18\x03 \x01(\tR\rinteractionId\x12+\n" +
	"\x11expected_revision\x18\x04 \x01(\x04R\x10expectedRevision\x12\x1b\n" +
	"\toption_id\x18\x05 \x01(\tR\boptionId\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\"v\n" +
	"\x13GetExecutionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\x12!\n" +
	"\fexecution_id\x18\x03 \x01(\tR\vexecutionId\"y\n" +
	"\x16CancelExecutionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\x12!\n" +
	"\fexecution_id\x18\x03 \x01(\tR\vexecutionId\"}\n" +
	"\vViewRequest\x12-\n" +
	"\x04open\x18\x01 \x01(\v2\x17.gatewayrpc.v1.OpenViewH\x00R\x04open\x126\n" +
	"\acommand\x18\x02 \x01(\v2\x1a.gatewayrpc.v1.ViewCommandH\x00R\acommandB\a\n" +
	"\x05frame\"i\n" +
	"\bOpenView\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rtrajectory_id\x18\x02 \x01(\tR\ftrajectoryId\x12\x1f\n" +
	"\vafter_event\x18\x03 \x01(\x04R\n" +
	"afterEvent\"\xae\x03\n" +
	"\vViewCommand\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12F\n" +
	"\renqueue_input\x18\x02 \x01(\v2\x1f.gatewayrpc.v1.ViewEnqueueInputH\x00R\fenqueueInput\x12C\n" +
	"\fcancel_input\x18\x03 \x01(\v2\x1e.gatewayrpc.v1.ViewCancelInputH\x00R\vcancelInput\x12X\n" +
	"\x13resolve_interaction\x18\x04 \x01(\v2%.gatewayrpc.v1.ViewResolveInteractionH\x00R\x12resolveInteraction\x12=\n" +
	"\n" +
	"set_paused\x18\x05 \x01(\v2\x1c.gatewayrpc.v1.ViewSetPausedH\x00R\tsetPaused\x12O\n" +
	"\x10cancel_execution\x18\x06 \x01(\v2\".gatewayrpc.v1.ViewCancelExecutionH\x00R\x0fcancelExecutionB\t\n" +
	"\acommand\"G\n" +
	"\x10ViewEnqueueInput\x12\x19\n" +
	"\binput_id\x18\x01 \x01(\tR\ainputId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"Y\n" +
	"\x0fViewCancelInput\x12\x19\n" +
	"\binput_id\x18\x01 \x01(\tR\ainputId\x12+\n" +
	"\x11expected_revision\x18\x02 \x01(\x04R\x10expectedRevision\"\x9d\x01\n" +
	"\x16ViewResolveInteraction\x12%\n" +
	"\x0einteraction_id\x18\x01 \x01(\tR\rinteractionId\x12+\n" +
	"\x11expected_revision\x18\x02 \x01(\x04R\x10expectedRevision\x12\x1b\n" +
	"\toption_id\x18\x03 \x01(\tR\boptionId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"T\n" +
	"\rViewSetPaused\x12\x16\n" +
	"\x06paused\x18\x01 \x01(\bR\x06paused\x12+\n" +
	"\x11expected_revision\x18\x02 \x01(\x04R\x10expectedRevision\"8\n" +
	"\x13ViewCancelExecution\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"\xe8\x01\n" +
	"\fViewResponse\x120\n" +
	"\x05ready\x18\x01 \x01(\v2\x18.gatewayrpc.v1.ViewReadyH\x00R\x05ready\x120\n" +
	"\x05event\x18\x02 \x01(\v2\x18.gatewayrpc.v1.ViewEventH\x00R\x05event\x123\n" +
	"\x06result\x18\x03 \x01(\v2\x19.gatewayrpc.v1.ViewResultH\x00R\x06result\x126\n" +
	"\afailure\x18\x04 \x01(\v2\x1a.gatewayrpc.v1.ViewFailureH\x00R\afailureB\a\n" +
	"\x05frame\"]\n" +
	"\tViewReady\x128\n" +
	"\n" +
	"trajectory\x18\x01 \x01(\v2\x18.gatewayrpc.v1.JsonValueR\n" +
	"trajectory\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\x04R\x06cursor\";\n" +
	"\tViewEvent\x12.\n" +
	"\x05event\x18\x01 \x01(\v2\x18.gatewayrpc.v1.JsonValueR\x05event\"[\n" +
	"\n" +
	"ViewResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.gatewayrpc.v1.JsonValueR\x05value\"Z\n" +
	"\vViewFailure\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xff\x0f\n" +
	"\x0eGatewayService\x12E\n" +
	"\x06Health\x12\x1c.gatewayrpc.v1.HealthRequest\x1a\x1d.gatewayrpc.v1.HealthResponse\x12T\n" +
	"\x10CreateTrajectory\x12&.gatewayrpc.v1.CreateTrajectoryRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12N\n" +
	"\rGetTrajectory\x12#.gatewayrpc.v1.GetTrajectoryRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12T\n" +
	"\x10ListTrajectories\x12&.gatewayrpc.v1.ListTrajectoriesRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12P\n" +
	"\x0eLoadTrajectory\x12$.gatewayrpc.v1.LoadTrajectoryRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12T\n" +
	"\x10ListConversation\x12&.gatewayrpc.v1.ListConversationRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12^\n" +
	"\x15ListTrajectoryEntries\x12+.gatewayrpc.v1.ListTrajectoryEntriesRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12X\n" +
	"\x12RollbackTrajectory\x12(.gatewayrpc.v1.RollbackTrajectoryRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12L\n" +
	"\fAttachPlugin\x12\".gatewayrpc.v1.AttachPluginRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12L\n" +
	"\fDetachPlugin\x12\".gatewayrpc.v1.DetachPluginRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12N\n" +
	"\rSubmitMessage\x12#.gatewayrpc.v1.SubmitMessageRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12b\n" +
	"\x17EnqueueContextInjection\x12-.gatewayrpc.v1.EnqueueContextInjectionRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12L\n" +
	"\fEnqueueInput\x12\".gatewayrpc.v1.EnqueueInputRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12D\n" +
	"\bGetInput\x12\x1e.gatewayrpc.v1.GetInputRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12H\n" +
	"\n" +
	"ListInputs\x12 .gatewayrpc.v1.ListInputsRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12J\n" +
	"\vCancelInput\x12!.gatewayrpc.v1.CancelInputRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12F\n" +
	"\tSetPaused\x12\x1f.gatewayrpc.v1.SetPausedRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12H\n" +
	"\n" +
	"ListEvents\x12 .gatewayrpc.v1.ListEventsRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12P\n" +
	"\x0eGetEventCursor\x12$.gatewayrpc.v1.GetEventCursorRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12P\n" +
	"\x0eGetInteraction\x12$.gatewayrpc.v1.GetInteractionRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12T\n" +
	"\x10ListInteractions\x12&.gatewayrpc.v1.ListInteractionsRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12X\n" +
	"\x12ResolveInteraction\x12(.gatewayrpc.v1.ResolveInteractionRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12L\n" +
	"\fGetExecution\x12\".gatewayrpc.v1.GetExecutionRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12R\n" +
	"\x0fCancelExecution\x12%.gatewayrpc.v1.CancelExecutionRequest\x1a\x18.gatewayrpc.v1.JsonValue\x12F\n" +
	"\aConnect\x12\x1a.gatewayrpc.v1.ViewRequest\x1a\x1b.gatewayrpc.v1.ViewResponse(\x010\x01B/Z-github.com/lincyaw/ag/gatewayrpc/v1;gatewayv1b\x06proto3"

var (
	file_gatewayrpc_v1_gateway_proto_rawDescOnce sync.Once
	file_gatewayrpc_v1_gateway_proto_rawDescData []byte
)

func file_gatewayrpc_v1_gateway_proto_rawDescGZIP() []byte {
	file_gatewayrpc_v1_gateway_proto_rawDescOnce.Do(func() {
		file_gatewayrpc_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gatewayrpc_v1_gateway_proto_rawDesc), len(file_gatewayrpc_v1_gateway_proto_rawDesc)))
	})
	return file_gatewayrpc_v1_gateway_proto_rawDescData
}

var file_gatewayrpc_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_gatewayrpc_v1_gateway_proto_goTypes = []any{
	(*HealthRequest)(nil),                  // 0: gatewayrpc.v1.HealthRequest
	(*HealthResponse)(nil),                 // 1: gatewayrpc.v1.HealthResponse
	(*JsonValue)(nil),                      // 2: gatewayrpc.v1.JsonValue
	(*CreateTrajectoryRequest)(nil),        // 3: gatewayrpc.v1.CreateTrajectoryRequest
	(*GetTrajectoryRequest)(nil),           // 4: gatewayrpc.v1.GetTrajectoryRequest
	(*ListTrajectoriesRequest)(nil),        // 5: gatewayrpc.v1.ListTrajectoriesRequest
	(*LoadTrajectoryRequest)(nil),          // 6: gatewayrpc.v1.LoadTrajectoryRequest
	(*ListConversationRequest)(nil),        // 7: gatewayrpc.v1.ListConversationRequest
	(*ListTrajectoryEntriesRequest)(nil),   // 8: gatewayrpc.v1.ListTrajectoryEntriesRequest
	(*RollbackTrajectoryRequest)(nil),      // 9: gatewayrpc.v1.RollbackTrajectoryRequest
	(*AttachPluginRequest)(nil),            // 10: gatewayrpc.v1.AttachPluginRequest
	(*DetachPluginRequest)(nil),            // 11: gatewayrpc.v1.DetachPluginRequest
	(*SubmitMessageRequest)(nil),           // 12: gatewayrpc.v1.SubmitMessageRequest
	(*EnqueueContextInjectionRequest)(nil), // 13: gatewayrpc.v1.EnqueueContextInjectionRequest
	(*EnqueueInputRequest)(nil),            // 14: gatewayrpc.v1.EnqueueInputRequest
	(*GetInputRequest)(nil),                // 15: gatewayrpc.v1.GetInputRequest
	(*ListInputsRequest)(nil),              // 16: gatewayrpc.v1.ListInputsRequest
	(*CancelInputRequest)(nil),             // 17: gatewayrpc.v1.CancelInputRequest
	(*SetPausedRequest)(nil),               // 18: gatewayrpc.v1.SetPausedRequest
	(*ListEventsRequest)(nil),              // 19: gatewayrpc.v1.ListEventsRequest
	(*GetEventCursorRequest)(nil),          // 20: gatewayrpc.v1.GetEventCursorRequest
	(*GetInteractionRequest)(nil),          // 21: gatewayrpc.v1.GetInteractionRequest
	(*ListInteractionsRequest)(nil),        // 22: gatewayrpc.v1.ListInteractionsRequest
	(*ResolveInteractionRequest)(nil),      // 23: gatewayrpc.v1.ResolveInteractionRequest
	(*GetExecutionRequest)(nil),            // 24: gatewayrpc.v1.GetExecutionRequest
	(*CancelExecutionRequest)(nil),         // 25: gatewayrpc.v1.CancelExecutionRequest
	(*ViewRequest)(nil),                    // 26: gatewayrpc.v1.ViewRequest
	(*OpenView)(nil),                       // 27: gatewayrpc.v1.OpenView
	(*ViewCommand)(nil),                    // 28: gatewayrpc.v1.ViewCommand
	(*ViewEnqueueInput)(nil),               // 29: gatewayrpc.v1.ViewEnqueueInput
	(*ViewCancelInput)(nil),                // 30: gatewayrpc.v1.ViewCancelInput
	(*ViewResolveInteraction)(nil),         // 31: gatewayrpc.v1.ViewResolveInteraction
	(*ViewSetPaused)(nil),                  // 32: gatewayrpc.v1.ViewSetPaused
	(*ViewCancelExecution)(nil),            // 33: gatewayrpc.v1.ViewCancelExecution
	(*ViewResponse)(nil),                   // 34: gatewayrpc.v1.ViewResponse
	(*ViewReady)(nil),                      // 35: gatewayrpc.v1.ViewReady
	(*ViewEvent)(nil),                      // 36: gatewayrpc.v1.ViewEvent
	(*ViewResult)(nil),                     // 37: gatewayrpc.v1.ViewResult
	(*ViewFailure)(nil),                    // 38: gatewayrpc.v1.ViewFailure
}
var file_gatewayrpc_v1_gateway_proto_depIdxs = []int32{
	27, // 0: gatewayrpc.v1.ViewRequest.open:type_name -> gatewayrpc.v1.OpenView
	28, // 1: gatewayrpc.v1.ViewRequest.command:type_name -> gatewayrpc.v1.ViewCommand
	29, // 2: gatewayrpc.v1.ViewCommand.enqueue_input:type_name -> gatewayrpc.v1.ViewEnqueueInput
	30, // 3: gatewayrpc.v1.ViewCommand.cancel_input:type_name -> gatewayrpc.v1.ViewCancelInput
	31, // 4: gatewayrpc.v1.ViewCommand.resolve_interaction:type_name -> gatewayrpc.v1.ViewResolveInteraction
	32, // 5: gatewayrpc.v1.ViewCommand.set_paused:type_name -> gatewayrpc.v1.ViewSetPaused
	33, // 6: gatewayrpc.v1.ViewCommand.cancel_execution:type_name -> gatewayrpc.v1.ViewCancelExecution
	35, // 7: gatewayrpc.v1.ViewResponse.ready:type_name -> gatewayrpc.v1.ViewReady
	36, // 8: gatewayrpc.v1.ViewResponse.event:type_name -> gatewayrpc.v1.ViewEvent
	37, // 9: gatewayrpc.v1.ViewResponse.result:type_name -> gatewayrpc.v1.ViewResult
	38, // 10: gatewayrpc.v1.ViewResponse.failure:type_name -> gatewayrpc.v1.ViewFailure
	2,  // 11: gatewayrpc.v1.ViewReady.trajectory:type_name -> gatewayrpc.v1.JsonValue
	2,  // 12: gatewayrpc.v1.ViewEvent.event:type_name -> gatewayrpc.v1.JsonValue
	2,  // 13: gatewayrpc.v1.ViewResult.value:type_name -> gatewayrpc.v1.JsonValue
	0,  // 14: gatewayrpc.v1.GatewayService.Health:input_type -> gatewayrpc.v1.HealthRequest
	3,  // 15: gatewayrpc.v1.GatewayService.CreateTrajectory:input_type -> gatewayrpc.v1.CreateTrajectoryRequest
	4,  // 16: gatewayrpc.v1.GatewayService.GetTrajectory:input_type -> gatewayrpc.v1.GetTrajectoryRequest
	5,  // 17: gatewayrpc.v1.GatewayService.ListTrajectories:input_type -> gatewayrpc.v1.ListTrajectoriesRequest
	6,  // 18: gatewayrpc.v1.GatewayService.LoadTrajectory:input_type -> gatewayrpc.v1.LoadTrajectoryRequest
	7,  // 19: gatewayrpc.v1.GatewayService.ListConversation:input_type -> gatewayrpc.v1.ListConversationRequest
	8,  // 20: gatewayrpc.v1.GatewayService.ListTrajectoryEntries:input_type -> gatewayrpc.v1.ListTrajectoryEntriesRequest
	9,  // 21: gatewayrpc.v1.GatewayService.RollbackTrajectory:input_type -> gatewayrpc.v1.RollbackTrajectoryRequest
	10, // 22: gatewayrpc.v1.GatewayService.AttachPlugin:input_type -> gatewayrpc.v1.AttachPluginRequest
	11, // 23: gatewayrpc.v1.GatewayService.DetachPlugin:input_type -> gatewayrpc.v1.DetachPluginRequest
	12, // 24: gatewayrpc.v1.GatewayService.SubmitMessage:input_type -> gatewayrpc.v1.SubmitMessageRequest
	13, // 25: gatewayrpc.v1.GatewayService.EnqueueContextInjection:input_type -> gatewayrpc.v1.EnqueueContextInjectionRequest
	14, // 26: gatewayrpc.v1.GatewayService.EnqueueInput:input_type -> gatewayrpc.v1.EnqueueInputRequest
	15, // 27: gatewayrpc.v1.GatewayService.GetInput:input_type -> gatewayrpc.v1.GetInputRequest
	16, // 28: gatewayrpc.v1.GatewayService.ListInputs:input_type -> gatewayrpc.v1.ListInputsRequest
	17, // 29: gatewayrpc.v1.GatewayService.CancelInput:input_type -> gatewayrpc.v1.CancelInputRequest
	18, // 30: gatewayrpc.v1.GatewayService.SetPaused:input_type -> gatewayrpc.v1.SetPausedRequest
	19, // 31: gatewayrpc.v1.GatewayService.ListEvents:input_type -> gatewayrpc.v1.ListEventsRequest
	20, // 32: gatewayrpc.v1.GatewayService.GetEventCursor:input_type -> gatewayrpc.v1.GetEventCursorRequest
	21, // 33: gatewayrpc.v1.GatewayService.GetInteraction:input_type -> gatewayrpc.v1.GetInteractionRequest
	22, // 34: gatewayrpc.v1.GatewayService.ListInteractions:input_type -> gatewayrpc.v1.ListInteractionsRequest
	23, // 35: gatewayrpc.v1.GatewayService.ResolveInteraction:input_type -> gatewayrpc.v1.ResolveInteractionRequest
	24, // 36: gatewayrpc.v1.GatewayService.GetExecution:input_type -> gatewayrpc.v1.GetExecutionRequest
	25, // 37: gatewayrpc.v1.GatewayService.CancelExecution:input_type -> gatewayrpc.v1.CancelExecutionRequest
	26, // 38: gatewayrpc.v1.GatewayService.Connect:input_type -> gatewayrpc.v1.ViewRequest
	1,  // 39: gatewayrpc.v1.GatewayService.Health:output_type -> gatewayrpc.v1.HealthResponse
	2,  // 40: gatewayrpc.v1.GatewayService.CreateTrajectory:output_type -> gatewayrpc.v1.JsonValue
	2,  // 41: gatewayrpc.v1.GatewayService.GetTrajectory:output_type -> gatewayrpc.v1.JsonValue
	2,  // 42: gatewayrpc.v1.GatewayService.ListTrajectories:output_type -> gatewayrpc.v1.JsonValue
	2,  // 43: gatewayrpc.v1.GatewayService.LoadTrajectory:output_type -> gatewayrpc.v1.JsonValue
	2,  // 44: gatewayrpc.v1.GatewayService.ListConversation:output_type -> gatewayrpc.v1.JsonValue
	2,  // 45: gatewayrpc.v1.GatewayService.ListTrajectoryEntries:output_type -> gatewayrpc.v1.JsonValue
	2,  // 46: gatewayrpc.v1.GatewayService.RollbackTrajectory:output_type -> gatewayrpc.v1.JsonValue
	2,  // 47: gatewayrpc.v1.GatewayService.AttachPlugin:output_type -> gatewayrpc.v1.JsonValue
	2,  // 48: gatewayrpc.v1.GatewayService.DetachPlugin:output_type -> gatewayrpc.v1.JsonValue
	2,  // 49: gatewayrpc.v1.GatewayService.SubmitMessage:output_type -> gatewayrpc.v1.JsonValue
	2,  // 50: gatewayrpc.v1.GatewayService.EnqueueContextInjection:output_type -> gatewayrpc.v1.JsonValue
	2,  // 51: gatewayrpc.v1.GatewayService.EnqueueInput:output_type -> gatewayrpc.v1.JsonValue
	2,  // 52: gatewayrpc.v1.GatewayService.GetInput:output_type -> gatewayrpc.v1.JsonValue
	2,  // 53: gatewayrpc.v1.GatewayService.ListInputs:output_type -> gatewayrpc.v1.JsonValue
	2,  // 54: gatewayrpc.v1.GatewayService.CancelInput:output_type -> gatewayrpc.v1.JsonValue
	2,  // 55: gatewayrpc.v1.GatewayService.SetPaused:output_type -> gatewayrpc.v1.JsonValue
	2,  // 56: gatewayrpc.v1.GatewayService.ListEvents:output_type -> gatewayrpc.v1.JsonValue
	2,  // 57: gatewayrpc.v1.GatewayService.GetEventCursor:output_type -> gatewayrpc.v1.JsonValue
	2,  // 58: gatewayrpc.v1.GatewayService.GetInteraction:output_type -> gatewayrpc.v1.JsonValue
	2,  // 59: gatewayrpc.v1.GatewayService.ListInteractions:output_type -> gatewayrpc.v1.JsonValue
	2,  // 60: gatewayrpc.v1.GatewayService.ResolveInteraction:output_type -> gatewayrpc.v1.JsonValue
	2,  // 61: gatewayrpc.v1.GatewayService.GetExecution:output_type -> gatewayrpc.v1.JsonValue
	2,  // 62: gatewayrpc.v1.GatewayService.CancelExecution:output_type -> gatewayrpc.v1.JsonValue
	34, // 63: gatewayrpc.v1.GatewayService.Connect:output_type -> gatewayrpc.v1.ViewResponse
	39, // [39:64] is the sub-list for method output_type
	14, // [14:39] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_gatewayrpc_v1_gateway_proto_init() }
func file_gatewayrpc_v1_gateway_proto_init() {
	if File_gatewayrpc_v1_gateway_proto != nil {
		return
	}
	file_gatewayrpc_v1_gateway_proto_msgTypes[26].OneofWrappers = []any{
		(*ViewRequest_Open)(nil),
		(*ViewRequest_Command)(nil),
	}
	file_gatewayrpc_v1_gateway_proto_msgTypes[28].OneofWrappers = []any{
		(*ViewCommand_EnqueueInput)(nil),
		(*ViewCommand_CancelInput)(nil),
		(*ViewCommand_ResolveInteraction)(nil),
		(*ViewCommand_SetPaused)(nil),
		(*ViewCommand_CancelExecution)(nil),
	}
	file_gatewayrpc_v1_gateway_proto_msgTypes[34].OneofWrappers = []any{
		(*ViewResponse_Ready)(nil),
		(*ViewResponse_Event)(nil),
		(*ViewResponse_Result)(nil),
		(*ViewResponse_Failure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gatewayrpc_v1_gateway_proto_rawDesc), len(file_gatewayrpc_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gatewayrpc_v1_gateway_proto_goTypes,
		DependencyIndexes: file_gatewayrpc_v1_gateway_proto_depIdxs,
		MessageInfos:      file_gatewayrpc_v1_gateway_proto_msgTypes,
	}.Build()
	File_gatewayrpc_v1_gateway_proto = out.File
	file_gatewayrpc_v1_gateway_proto_goTypes = nil
	file_gatewayrpc_v1_gateway_proto_depIdxs = nil
}
