// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pluginrpc/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FailurePolicy int32

const (
	FailurePolicy_FAILURE_POLICY_UNSPECIFIED FailurePolicy = 0
	FailurePolicy_FAILURE_POLICY_FAIL_CLOSED FailurePolicy = 1
	FailurePolicy_FAILURE_POLICY_CONTINUE    FailurePolicy = 2
)

// Enum value maps for FailurePolicy.
var (
	FailurePolicy_name = map[int32]string{
		0: "FAILURE_POLICY_UNSPECIFIED",
		1: "FAILURE_POLICY_FAIL_CLOSED",
		2: "FAILURE_POLICY_CONTINUE",
	}
	FailurePolicy_value = map[string]int32{
		"FAILURE_POLICY_UNSPECIFIED": 0,
		"FAILURE_POLICY_FAIL_CLOSED": 1,
		"FAILURE_POLICY_CONTINUE":    2,
	}
)

func (x FailurePolicy) Enum() *FailurePolicy {
	p := new(FailurePolicy)
	*p = x
	return p
}

func (x FailurePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailurePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_pluginrpc_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (FailurePolicy) Type() protoreflect.EnumType {
	return &file_pluginrpc_v1_plugin_proto_enumTypes[0]
}

func (x FailurePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailurePolicy.Descriptor instead.
func (FailurePolicy) EnumDescriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{0}
}

type ActionKind int32

const (
	ActionKind_ACTION_KIND_UNSPECIFIED ActionKind = 0
	ActionKind_ACTION_KIND_STEP        ActionKind = 1
	ActionKind_ACTION_KIND_STOP        ActionKind = 2
	ActionKind_ACTION_KIND_INJECT      ActionKind = 3
)

// Enum value maps for ActionKind.
var (
	ActionKind_name = map[int32]string{
		0: "ACTION_KIND_UNSPECIFIED",
		1: "ACTION_KIND_STEP",
		2: "ACTION_KIND_STOP",
		3: "ACTION_KIND_INJECT",
	}
	ActionKind_value = map[string]int32{
		"ACTION_KIND_UNSPECIFIED": 0,
		"ACTION_KIND_STEP":        1,
		"ACTION_KIND_STOP":        2,
		"ACTION_KIND_INJECT":      3,
	}
)

func (x ActionKind) Enum() *ActionKind {
	p := new(ActionKind)
	*p = x
	return p
}

func (x ActionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_pluginrpc_v1_plugin_proto_enumTypes[1].Descriptor()
}

func (ActionKind) Type() protoreflect.EnumType {
	return &file_pluginrpc_v1_plugin_proto_enumTypes[1]
}

func (x ActionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionKind.Descriptor instead.
func (ActionKind) EnumDescriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{1}
}

type OperationState int32

const (
	OperationState_OPERATION_STATE_UNSPECIFIED OperationState = 0
	OperationState_OPERATION_STATE_PENDING     OperationState = 1
	OperationState_OPERATION_STATE_RUNNING     OperationState = 2
	OperationState_OPERATION_STATE_SUCCEEDED   OperationState = 3
	OperationState_OPERATION_STATE_FAILED      OperationState = 4
	OperationState_OPERATION_STATE_CANCELLED   OperationState = 5
)

// Enum value maps for OperationState.
var (
	OperationState_name = map[int32]string{
		0: "OPERATION_STATE_UNSPECIFIED",
		1: "OPERATION_STATE_PENDING",
		2: "OPERATION_STATE_RUNNING",
		3: "OPERATION_STATE_SUCCEEDED",
		4: "OPERATION_STATE_FAILED",
		5: "OPERATION_STATE_CANCELLED",
	}
	OperationState_value = map[string]int32{
		"OPERATION_STATE_UNSPECIFIED": 0,
		"OPERATION_STATE_PENDING":     1,
		"OPERATION_STATE_RUNNING":     2,
		"OPERATION_STATE_SUCCEEDED":   3,
		"OPERATION_STATE_FAILED":      4,
		"OPERATION_STATE_CANCELLED":   5,
	}
)

func (x OperationState) Enum() *OperationState {
	p := new(OperationState)
	*p = x
	return p
}

func (x OperationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationState) Descriptor() protoreflect.EnumDescriptor {
	return file_pluginrpc_v1_plugin_proto_enumTypes[2].Descriptor()
}

func (OperationState) Type() protoreflect.EnumType {
	return &file_pluginrpc_v1_plugin_proto_enumTypes[2]
}

func (x OperationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationState.Descriptor instead.
func (OperationState) EnumDescriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{2}
}

type OperationKind int32

const (
	OperationKind_OPERATION_KIND_UNSPECIFIED OperationKind = 0
	OperationKind_OPERATION_KIND_PROVIDER    OperationKind = 1
	OperationKind_OPERATION_KIND_TOOL        OperationKind = 2
	OperationKind_OPERATION_KIND_CAPABILITY  OperationKind = 3
)

// Enum value maps for OperationKind.
var (
	OperationKind_name = map[int32]string{
		0: "OPERATION_KIND_UNSPECIFIED",
		1: "OPERATION_KIND_PROVIDER",
		2: "OPERATION_KIND_TOOL",
		3: "OPERATION_KIND_CAPABILITY",
	}
	OperationKind_value = map[string]int32{
		"OPERATION_KIND_UNSPECIFIED": 0,
		"OPERATION_KIND_PROVIDER":    1,
		"OPERATION_KIND_TOOL":        2,
		"OPERATION_KIND_CAPABILITY":  3,
	}
)

func (x OperationKind) Enum() *OperationKind {
	p := new(OperationKind)
	*p = x
	return p
}

func (x OperationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_pluginrpc_v1_plugin_proto_enumTypes[3].Descriptor()
}

func (OperationKind) Type() protoreflect.EnumType {
	return &file_pluginrpc_v1_plugin_proto_enumTypes[3]
}

func (x OperationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationKind.Descriptor instead.
func (OperationKind) EnumDescriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{3}
}

type Manifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ApiVersion    uint32                 `protobuf:"varint,4,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Requires      []string               `protobuf:"bytes,5,rep,name=requires,proto3" json:"requires,omitempty"`
	Conflicts     []string               `protobuf:"bytes,6,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	Registers     []string               `protobuf:"bytes,7,rep,name=registers,proto3" json:"registers,omitempty"`
	MinApiVersion uint32                 `protobuf:"varint,8,opt,name=min_api_version,json=minApiVersion,proto3" json:"min_api_version,omitempty"`
	MaxApiVersion uint32                 `protobuf:"varint,9,opt,name=max_api_version,json=maxApiVersion,proto3" json:"max_api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manifest) Reset() {
	*x = Manifest{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manifest) ProtoMessage() {}

func (x *Manifest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manifest.ProtoReflect.Descriptor instead.
func (*Manifest) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Manifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Manifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Manifest) GetApiVersion() uint32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *Manifest) GetRequires() []string {
	if x != nil {
		return x.Requires
	}
	return nil
}

func (x *Manifest) GetConflicts() []string {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

func (x *Manifest) GetRegisters() []string {
	if x != nil {
		return x.Registers
	}
	return nil
}

func (x *Manifest) GetMinApiVersion() uint32 {
	if x != nil {
		return x.MinApiVersion
	}
	return 0
}

func (x *Manifest) GetMaxApiVersion() uint32 {
	if x != nil {
		return x.MaxApiVersion
	}
	return 0
}

type ProviderSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderSpec) Reset() {
	*x = ProviderSpec{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderSpec) ProtoMessage() {}

func (x *ProviderSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderSpec.ProtoReflect.Descriptor instead.
func (*ProviderSpec) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ProviderSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderSpec) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ToolSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    *structpb.Struct       `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolSpec) Reset() {
	*x = ToolSpec{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolSpec) ProtoMessage() {}

func (x *ToolSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolSpec.ProtoReflect.Descriptor instead.
func (*ToolSpec) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ToolSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolSpec) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type HookSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	FailurePolicy FailurePolicy          `protobuf:"varint,4,opt,name=failure_policy,json=failurePolicy,proto3,enum=pluginrpc.v1.FailurePolicy" json:"failure_policy,omitempty"`
	TimeoutMillis int64                  `protobuf:"varint,5,opt,name=timeout_millis,json=timeoutMillis,proto3" json:"timeout_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookSpec) Reset() {
	*x = HookSpec{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookSpec) ProtoMessage() {}

func (x *HookSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookSpec.ProtoReflect.Descriptor instead.
func (*HookSpec) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *HookSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HookSpec) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *HookSpec) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *HookSpec) GetFailurePolicy() FailurePolicy {
	if x != nil {
		return x.FailurePolicy
	}
	return FailurePolicy_FAILURE_POLICY_UNSPECIFIED
}

func (x *HookSpec) GetTimeoutMillis() int64 {
	if x != nil {
		return x.TimeoutMillis
	}
	return 0
}

type SubscriberSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Events        []string               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	TimeoutMillis int64                  `protobuf:"varint,3,opt,name=timeout_millis,json=timeoutMillis,proto3" json:"timeout_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriberSpec) Reset() {
	*x = SubscriberSpec{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriberSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriberSpec) ProtoMessage() {}

func (x *SubscriberSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriberSpec.ProtoReflect.Descriptor instead.
func (*SubscriberSpec) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *SubscriberSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubscriberSpec) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *SubscriberSpec) GetTimeoutMillis() int64 {
	if x != nil {
		return x.TimeoutMillis
	}
	return 0
}

type CapabilitySpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InputSchema   *structpb.Struct       `protobuf:"bytes,3,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	OutputSchema  *structpb.Struct       `protobuf:"bytes,4,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitySpec) Reset() {
	*x = CapabilitySpec{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitySpec) ProtoMessage() {}

func (x *CapabilitySpec) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitySpec.ProtoReflect.Descriptor instead.
func (*CapabilitySpec) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *CapabilitySpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CapabilitySpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CapabilitySpec) GetInputSchema() *structpb.Struct {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

func (x *CapabilitySpec) GetOutputSchema() *structpb.Struct {
	if x != nil {
		return x.OutputSchema
	}
	return nil
}

type EventContract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MutableFields []string               `protobuf:"bytes,2,rep,name=mutable_fields,json=mutableFields,proto3" json:"mutable_fields,omitempty"`
	AllowBlock    bool                   `protobuf:"varint,3,opt,name=allow_block,json=allowBlock,proto3" json:"allow_block,omitempty"`
	AllowAction   bool                   `protobuf:"varint,4,opt,name=allow_action,json=allowAction,proto3" json:"allow_action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventContract) Reset() {
	*x = EventContract{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventContract) ProtoMessage() {}

func (x *EventContract) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventContract.ProtoReflect.Descriptor instead.
func (*EventContract) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *EventContract) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventContract) GetMutableFields() []string {
	if x != nil {
		return x.MutableFields
	}
	return nil
}

func (x *EventContract) GetAllowBlock() bool {
	if x != nil {
		return x.AllowBlock
	}
	return false
}

func (x *EventContract) GetAllowAction() bool {
	if x != nil {
		return x.AllowAction
	}
	return false
}

type DescribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *Manifest              `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Providers     []*ProviderSpec        `protobuf:"bytes,2,rep,name=providers,proto3" json:"providers,omitempty"`
	Tools         []*ToolSpec            `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	Hooks         []*HookSpec            `protobuf:"bytes,4,rep,name=hooks,proto3" json:"hooks,omitempty"`
	Capabilities  []*CapabilitySpec      `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Events        []*EventContract       `protobuf:"bytes,6,rep,name=events,proto3" json:"events,omitempty"`
	Subscribers   []*SubscriberSpec      `protobuf:"bytes,7,rep,name=subscribers,proto3" json:"subscribers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *DescribeResponse) GetManifest() *Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *DescribeResponse) GetProviders() []*ProviderSpec {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *DescribeResponse) GetTools() []*ToolSpec {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *DescribeResponse) GetHooks() []*HookSpec {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *DescribeResponse) GetCapabilities() []*CapabilitySpec {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *DescribeResponse) GetEvents() []*EventContract {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *DescribeResponse) GetSubscribers() []*SubscriberSpec {
	if x != nil {
		return x.Subscribers
	}
	return nil
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{8}
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     *structpb.Struct       `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ToolCalls     []*ToolCall            `protobuf:"bytes,3,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	ToolCallId    string                 `protobuf:"bytes,4,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *Message) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

type Usage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   int64                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int64                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *Usage) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Usage) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

type ModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Tools         []*ToolSpec            `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelRequest) Reset() {
	*x = ModelRequest{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelRequest) ProtoMessage() {}

func (x *ModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelRequest.ProtoReflect.Descriptor instead.
func (*ModelRequest) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *ModelRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ModelRequest) GetTools() []*ToolSpec {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ToolCalls     []*ToolCall            `protobuf:"bytes,2,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	FinishReason  string                 `protobuf:"bytes,4,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelResponse) Reset() {
	*x = ModelResponse{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelResponse) ProtoMessage() {}

func (x *ModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelResponse.ProtoReflect.Descriptor instead.
func (*ModelResponse) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *ModelResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ModelResponse) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *ModelResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ModelResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *ModelResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	IsError       bool                   `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *ToolResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ToolResult) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type EventEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,4,opt,name=generation,proto3" json:"generation,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *EventEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventEnvelope) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventEnvelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EventEnvelope) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *EventEnvelope) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *Block) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Block) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type Cause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Final         bool                   `protobuf:"varint,3,opt,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cause) Reset() {
	*x = Cause{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cause) ProtoMessage() {}

func (x *Cause) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cause.ProtoReflect.Descriptor instead.
func (*Cause) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *Cause) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Cause) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Cause) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ActionKind             `protobuf:"varint,1,opt,name=kind,proto3,enum=pluginrpc.v1.ActionKind" json:"kind,omitempty"`
	Cause         *Cause                 `protobuf:"bytes,2,opt,name=cause,proto3" json:"cause,omitempty"`
	Messages      []*Message             `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *Action) GetKind() ActionKind {
	if x != nil {
		return x.Kind
	}
	return ActionKind_ACTION_KIND_UNSPECIFIED
}

func (x *Action) GetCause() *Cause {
	if x != nil {
		return x.Cause
	}
	return nil
}

func (x *Action) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Effect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patch         *structpb.Struct       `protobuf:"bytes,1,opt,name=patch,proto3" json:"patch,omitempty"`
	Block         *Block                 `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	Action        *Action                `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect) Reset() {
	*x = Effect{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect) ProtoMessage() {}

func (x *Effect) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect.ProtoReflect.Descriptor instead.
func (*Effect) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *Effect) GetPatch() *structpb.Struct {
	if x != nil {
		return x.Patch
	}
	return nil
}

func (x *Effect) GetBlock() *Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *Effect) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

type OperationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Input          *structpb.Struct       `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OperationRequest) Reset() {
	*x = OperationRequest{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequest) ProtoMessage() {}

func (x *OperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequest.ProtoReflect.Descriptor instead.
func (*OperationRequest) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *OperationRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *OperationRequest) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

type SubmitOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          OperationKind          `protobuf:"varint,1,opt,name=kind,proto3,enum=pluginrpc.v1.OperationKind" json:"kind,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Request       *OperationRequest      `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOperationRequest) Reset() {
	*x = SubmitOperationRequest{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOperationRequest) ProtoMessage() {}

func (x *SubmitOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOperationRequest.ProtoReflect.Descriptor instead.
func (*SubmitOperationRequest) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *SubmitOperationRequest) GetKind() OperationKind {
	if x != nil {
		return x.Kind
	}
	return OperationKind_OPERATION_KIND_UNSPECIFIED
}

func (x *SubmitOperationRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *SubmitOperationRequest) GetRequest() *OperationRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type SubmitOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *Operation             `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOperationResponse) Reset() {
	*x = SubmitOperationResponse{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOperationResponse) ProtoMessage() {}

func (x *SubmitOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOperationResponse.ProtoReflect.Descriptor instead.
func (*SubmitOperationResponse) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *SubmitOperationResponse) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

type PollOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          OperationKind          `protobuf:"varint,1,opt,name=kind,proto3,enum=pluginrpc.v1.OperationKind" json:"kind,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	AfterRevision uint64                 `protobuf:"varint,4,opt,name=after_revision,json=afterRevision,proto3" json:"after_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollOperationRequest) Reset() {
	*x = PollOperationRequest{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollOperationRequest) ProtoMessage() {}

func (x *PollOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollOperationRequest.ProtoReflect.Descriptor instead.
func (*PollOperationRequest) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *PollOperationRequest) GetKind() OperationKind {
	if x != nil {
		return x.Kind
	}
	return OperationKind_OPERATION_KIND_UNSPECIFIED
}

func (x *PollOperationRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PollOperationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PollOperationRequest) GetAfterRevision() uint64 {
	if x != nil {
		return x.AfterRevision
	}
	return 0
}

type PollOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *Operation             `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollOperationResponse) Reset() {
	*x = PollOperationResponse{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollOperationResponse) ProtoMessage() {}

func (x *PollOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollOperationResponse.ProtoReflect.Descriptor instead.
func (*PollOperationResponse) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *PollOperationResponse) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

type CancelOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          OperationKind          `protobuf:"varint,1,opt,name=kind,proto3,enum=pluginrpc.v1.OperationKind" json:"kind,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOperationRequest) Reset() {
	*x = CancelOperationRequest{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOperationRequest) ProtoMessage() {}

func (x *CancelOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOperationRequest.ProtoReflect.Descriptor instead.
func (*CancelOperationRequest) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *CancelOperationRequest) GetKind() OperationKind {
	if x != nil {
		return x.Kind
	}
	return OperationKind_OPERATION_KIND_UNSPECIFIED
}

func (x *CancelOperationRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CancelOperationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *Operation             `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOperationResponse) Reset() {
	*x = CancelOperationResponse{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOperationResponse) ProtoMessage() {}

func (x *CancelOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOperationResponse.ProtoReflect.Descriptor instead.
func (*CancelOperationResponse) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *CancelOperationResponse) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

type Operation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdempotencyKey     string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	State              OperationState         `protobuf:"varint,3,opt,name=state,proto3,enum=pluginrpc.v1.OperationState" json:"state,omitempty"`
	Revision           uint64                 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	Output             *structpb.Struct       `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	Error              string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	SubmittedUnixMilli int64                  `protobuf:"varint,7,opt,name=submitted_unix_milli,json=submittedUnixMilli,proto3" json:"submitted_unix_milli,omitempty"`
	UpdatedUnixMilli   int64                  `protobuf:"varint,8,opt,name=updated_unix_milli,json=updatedUnixMilli,proto3" json:"updated_unix_milli,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *Operation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Operation) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Operation) GetState() OperationState {
	if x != nil {
		return x.State
	}
	return OperationState_OPERATION_STATE_UNSPECIFIED
}

func (x *Operation) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Operation) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Operation) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Operation) GetSubmittedUnixMilli() int64 {
	if x != nil {
		return x.SubmittedUnixMilli
	}
	return 0
}

func (x *Operation) GetUpdatedUnixMilli() int64 {
	if x != nil {
		return x.UpdatedUnixMilli
	}
	return 0
}

type HandleHookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hook          string                 `protobuf:"bytes,1,opt,name=hook,proto3" json:"hook,omitempty"`
	Event         *EventEnvelope         `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleHookRequest) Reset() {
	*x = HandleHookRequest{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleHookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleHookRequest) ProtoMessage() {}

func (x *HandleHookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleHookRequest.ProtoReflect.Descriptor instead.
func (*HandleHookRequest) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *HandleHookRequest) GetHook() string {
	if x != nil {
		return x.Hook
	}
	return ""
}

func (x *HandleHookRequest) GetEvent() *EventEnvelope {
	if x != nil {
		return x.Event
	}
	return nil
}

type HandleHookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Effect        *Effect                `protobuf:"bytes,1,opt,name=effect,proto3" json:"effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleHookResponse) Reset() {
	*x = HandleHookResponse{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleHookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleHookResponse) ProtoMessage() {}

func (x *HandleHookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleHookResponse.ProtoReflect.Descriptor instead.
func (*HandleHookResponse) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{29}
}

func (x *HandleHookResponse) GetEffect() *Effect {
	if x != nil {
		return x.Effect
	}
	return nil
}

type Delivery struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sequence         uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Plugin           string                 `protobuf:"bytes,3,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Subscription     string                 `protobuf:"bytes,4,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Partition        string                 `protobuf:"bytes,5,opt,name=partition,proto3" json:"partition,omitempty"`
	Event            *EventEnvelope         `protobuf:"bytes,6,opt,name=event,proto3" json:"event,omitempty"`
	Attempt          int32                  `protobuf:"varint,7,opt,name=attempt,proto3" json:"attempt,omitempty"`
	PluginVersion    string                 `protobuf:"bytes,8,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	ResourceRevision string                 `protobuf:"bytes,9,opt,name=resource_revision,json=resourceRevision,proto3" json:"resource_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{30}
}

func (x *Delivery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Delivery) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Delivery) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *Delivery) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

func (x *Delivery) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *Delivery) GetEvent() *EventEnvelope {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Delivery) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Delivery) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *Delivery) GetResourceRevision() string {
	if x != nil {
		return x.ResourceRevision
	}
	return ""
}

type DeliverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivery      *Delivery              `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRequest) Reset() {
	*x = DeliverRequest{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRequest) ProtoMessage() {}

func (x *DeliverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRequest.ProtoReflect.Descriptor instead.
func (*DeliverRequest) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{31}
}

func (x *DeliverRequest) GetDelivery() *Delivery {
	if x != nil {
		return x.Delivery
	}
	return nil
}

type DeliverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverResponse) Reset() {
	*x = DeliverResponse{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverResponse) ProtoMessage() {}

func (x *DeliverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverResponse.ProtoReflect.Descriptor instead.
func (*DeliverResponse) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{32}
}

func (x *DeliverResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type Registration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Manifest      *Manifest              `protobuf:"bytes,3,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{33}
}

func (x *Registration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Registration) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Registration) GetManifest() *Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registration  *Registration          `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	TtlMillis     int64                  `protobuf:"varint,2,opt,name=ttl_millis,json=ttlMillis,proto3" json:"ttl_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{34}
}

func (x *RegisterRequest) GetRegistration() *Registration {
	if x != nil {
		return x.Registration
	}
	return nil
}

func (x *RegisterRequest) GetTtlMillis() int64 {
	if x != nil {
		return x.TtlMillis
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{35}
}

func (x *RegisterResponse) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type Lease struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpiresUnixMilli int64                  `protobuf:"varint,2,opt,name=expires_unix_milli,json=expiresUnixMilli,proto3" json:"expires_unix_milli,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Lease) Reset() {
	*x = Lease{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lease) ProtoMessage() {}

func (x *Lease) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lease.ProtoReflect.Descriptor instead.
func (*Lease) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{36}
}

func (x *Lease) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lease) GetExpiresUnixMilli() int64 {
	if x != nil {
		return x.ExpiresUnixMilli
	}
	return 0
}

type RenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TtlMillis     int64                  `protobuf:"varint,2,opt,name=ttl_millis,json=ttlMillis,proto3" json:"ttl_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewRequest) Reset() {
	*x = RenewRequest{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewRequest) ProtoMessage() {}

func (x *RenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewRequest.ProtoReflect.Descriptor instead.
func (*RenewRequest) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{37}
}

func (x *RenewRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RenewRequest) GetTtlMillis() int64 {
	if x != nil {
		return x.TtlMillis
	}
	return 0
}

type RenewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lease         *Lease                 `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewResponse) Reset() {
	*x = RenewResponse{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewResponse) ProtoMessage() {}

func (x *RenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewResponse.ProtoReflect.Descriptor instead.
func (*RenewResponse) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{38}
}

func (x *RenewResponse) GetLease() *Lease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type UnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRequest) Reset() {
	*x = UnregisterRequest{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRequest) ProtoMessage() {}

func (x *UnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRequest) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{39}
}

func (x *UnregisterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UnregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterResponse) Reset() {
	*x = UnregisterResponse{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterResponse) ProtoMessage() {}

func (x *UnregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterResponse.ProtoReflect.Descriptor instead.
func (*UnregisterResponse) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{40}
}

type ListRegistrationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegistrationsRequest) Reset() {
	*x = ListRegistrationsRequest{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegistrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegistrationsRequest) ProtoMessage() {}

func (x *ListRegistrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegistrationsRequest.ProtoReflect.Descriptor instead.
func (*ListRegistrationsRequest) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{41}
}

type ListRegistrationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registrations []*Registration        `protobuf:"bytes,1,rep,name=registrations,proto3" json:"registrations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRegistrationsResponse) Reset() {
	*x = ListRegistrationsResponse{}
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRegistrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRegistrationsResponse) ProtoMessage() {}

func (x *ListRegistrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginrpc_v1_plugin_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRegistrationsResponse.ProtoReflect.Descriptor instead.
func (*ListRegistrationsResponse) Descriptor() ([]byte, []int) {
	return file_pluginrpc_v1_plugin_proto_rawDescGZIP(), []int{42}
}

func (x *ListRegistrationsResponse) GetRegistrations() []*Registration {
	if x != nil {
		return x.Registrations
	}
	return nil
}

var File_pluginrpc_v1_plugin_proto protoreflect.FileDescriptor

const file_pluginrpc_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x19pluginrpc/v1/plugin.proto\x12\fpluginrpc.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xa3\x02\n" +
	"\bManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vapi_version\x18\x04 \x01(\rR\n" +
	"apiVersion\x12\x1a\n" +
	"\brequires\x18\x05 \x03(\tR\brequires\x12\x1c\n" +
	"\tconflicts\x18\x06 \x03(\tR\tconflicts\x12\x1c\n" +
	"\tregisters\x18\a \x03(\tR\tregisters\x12&\n" +
	"\x0fmin_api_version\x18\b \x01(\rR\rminApiVersion\x12&\n" +
	"\x0fmax_api_version\x18\t \x01(\rR\rmaxApiVersion\"8\n" +
	"\fProviderSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"y\n" +
	"\bToolSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x127\n" +
	"\n" +
	"parameters\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\"\xbb\x01\n" +
	"\bHookSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12B\n" +
	"\x0efailure_policy\x18\x04 \x01(\x0e2\x1b.pluginrpc.v1.FailurePolicyR\rfailurePolicy\x12%\n" +
	"\x0etimeout_millis\x18\x05 \x01(\x03R\rtimeoutMillis\"c\n" +
	"\x0eSubscriberSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06events\x18\x02 \x03(\tR\x06events\x12%\n" +
	"\x0etimeout_millis\x18\x03 \x01(\x03R\rtimeoutMillis\"\xc0\x01\n" +
	"\x0eCapabilitySpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12:\n" +
	"\finput_schema\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vinputSchema\x12<\n" +
	"\routput_schema\x18\x04 \x01(\v2\x17.google.protobuf.StructR\foutputSchema\"\x8e\x01\n" +
	"\rEventContract\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0emutable_fields\x18\x02 \x03(\tR\rmutableFields\x12\x1f\n" +
	"\vallow_block\x18\x03 \x01(\bR\n" +
	"allowBlock\x12!\n" +
	"\fallow_action\x18\x04 \x01(\bR\vallowAction\"\x93\x03\n" +
	"\x10DescribeResponse\x122\n" +
	"\bmanifest\x18\x01 \x01(\v2\x16.pluginrpc.v1.ManifestR\bmanifest\x128\n" +
	"\tproviders\x18\x02 \x03(\v2\x1a.pluginrpc.v1.ProviderSpecR\tproviders\x12,\n" +
	"\x05tools\x18\x03 \x03(\v2\x16.pluginrpc.v1.ToolSpecR\x05tools\x12,\n" +
	"\x05hooks\x18\x04 \x03(\v2\x16.pluginrpc.v1.HookSpecR\x05hooks\x12@\n" +
	"\fcapabilities\x18\x05 \x03(\v2\x1c.pluginrpc.v1.CapabilitySpecR\fcapabilities\x123\n" +
	"\x06events\x18\x06 \x03(\v2\x1b.pluginrpc.v1.EventContractR\x06events\x12>\n" +
	"\vsubscribers\x18\a \x03(\v2\x1c.pluginrpc.v1.SubscriberSpecR\vsubscribers\"\x11\n" +
	"\x0fDescribeRequest\"e\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\targuments\x18\x03 \x01(\v2\x17.google.protobuf.StructR\targuments\"\x90\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x125\n" +
	"\n" +
	"tool_calls\x18\x03 \x03(\v2\x16.pluginrpc.v1.ToolCallR\ttoolCalls\x12 \n" +
	"\ftool_call_id\x18\x04 \x01(\tR\n" +
	"toolCallId\"O\n" +
	"\x05Usage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x03R\foutputTokens\"o\n" +
	"\fModelRequest\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.pluginrpc.v1.MessageR\bmessages\x12,\n" +
	"\x05tools\x18\x02 \x03(\v2\x16.pluginrpc.v1.ToolSpecR\x05tools\"\xc6\x01\n" +
	"\rModelResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x125\n" +
	"\n" +
	"tool_calls\x18\x02 \x03(\v2\x16.pluginrpc.v1.ToolCallR\ttoolCalls\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12#\n" +
	"\rfinish_reason\x18\x04 \x01(\tR\ffinishReason\x12)\n" +
	"\x05usage\x18\x05 \x01(\v2\x13.pluginrpc.v1.UsageR\x05usage\"A\n" +
	"\n" +
	"ToolResult\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError\"\xa5\x01\n" +
	"\rEventEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1e\n" +
	"\n" +
	"generation\x18\x04 \x01(\x04R\n" +
	"generation\x121\n" +
	"\apayload\x18\x05 \x01(\v2\x17.google.protobuf.StructR\apayload\"3\n" +
	"\x05Block\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\"I\n" +
	"\x05Cause\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12\x14\n" +
	"\x05final\x18\x03 \x01(\bR\x05final\"\x94\x01\n" +
	"\x06Action\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.pluginrpc.v1.ActionKindR\x04kind\x12)\n" +
	"\x05cause\x18\x02 \x01(\v2\x13.pluginrpc.v1.CauseR\x05cause\x121\n" +
	"\bmessages\x18\x03 \x03(\v2\x15.pluginrpc.v1.MessageR\bmessages\"\x90\x01\n" +
	"\x06Effect\x12-\n" +
	"\x05patch\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x05patch\x12)\n" +
	"\x05block\x18\x02 \x01(\v2\x13.pluginrpc.v1.BlockR\x05block\x12,\n" +
	"\x06action\x18\x03 \x01(\v2\x14.pluginrpc.v1.ActionR\x06action\"j\n" +
	"\x10OperationRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12-\n" +
	"\x05input\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05input\"\x9f\x01\n" +
	"\x16SubmitOperationRequest\x12/\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1b.pluginrpc.v1.OperationKindR\x04kind\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x128\n" +
	"\arequest\x18\x03 \x01(\v2\x1e.pluginrpc.v1.OperationRequestR\arequest\"P\n" +
	"\x17SubmitOperationResponse\x125\n" +
	"\toperation\x18\x01 \x01(\v2\x17.pluginrpc.v1.OperationR\toperation\"\x9a\x01\n" +
	"\x14PollOperationRequest\x12/\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1b.pluginrpc.v1.OperationKindR\x04kind\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12%\n" +
	"\x0eafter_revision\x18\x04 \x01(\x04R\rafterRevision\"N\n" +
	"\x15PollOperationResponse\x125\n" +
	"\toperation\x18\x01 \x01(\v2\x17.pluginrpc.v1.OperationR\toperation\"u\n" +
	"\x16CancelOperationRequest\x12/\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1b.pluginrpc.v1.OperationKindR\x04kind\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"P\n" +
	"\x17CancelOperationResponse\x125\n" +
	"\toperation\x18\x01 \x01(\v2\x17.pluginrpc.v1.OperationR\toperation\"\xbb\x02\n" +
	"\tOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x122\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1c.pluginrpc.v1.OperationStateR\x05state\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x04R\brevision\x12/\n" +
	"\x06output\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06output\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x120\n" +
	"\x14submitted_unix_milli\x18\a \x01(\x03R\x12submittedUnixMilli\x12,\n" +
	"\x12updated_unix_milli\x18\b \x01(\x03R\x10updatedUnixMilli\"Z\n" +
	"\x11HandleHookRequest\x12\x12\n" +
	"\x04hook\x18\x01 \x01(\tR\x04hook\x121\n" +
	"\x05event\x18\x02 \x01(\v2\x1b.pluginrpc.v1.EventEnvelopeR\x05event\"B\n" +
	"\x12HandleHookResponse\x12,\n" +
	"\x06effect\x18\x01 \x01(\v2\x14.pluginrpc.v1.EffectR\x06effect\"\xb1\x02\n" +
	"\bDelivery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x16\n" +
	"\x06plugin\x18\x03 \x01(\tR\x06plugin\x12\"\n" +
	"\fsubscription\x18\x04 \x01(\tR\fsubscription\x12\x1c\n" +
	"\tpartition\x18\x05 \x01(\tR\tpartition\x121\n" +
	"\x05event\x18\x06 \x01(\v2\x1b.pluginrpc.v1.EventEnvelopeR\x05event\x12\x18\n" +
	"\aattempt\x18\a \x01(\x05R\aattempt\x12%\n" +
	"\x0eplugin_version\x18\b \x01(\tR\rpluginVersion\x12+\n" +
	"\x11resource_revision\x18\t \x01(\tR\x10resourceRevision\"D\n" +
	"\x0eDeliverRequest\x122\n" +
	"\bdelivery\x18\x01 \x01(\v2\x16.pluginrpc.v1.DeliveryR\bdelivery\"-\n" +
	"\x0fDeliverResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"h\n" +
	"\fRegistration\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x122\n" +
	"\bmanifest\x18\x03 \x01(\v2\x16.pluginrpc.v1.ManifestR\bmanifest\"p\n" +
	"\x0fRegisterRequest\x12>\n" +
	"\fregistration\x18\x01 \x01(\v2\x1a.pluginrpc.v1.RegistrationR\fregistration\x12\x1d\n" +
	"\n" +
	"ttl_millis\x18\x02 \x01(\x03R\tttlMillis\"=\n" +
	"\x10RegisterResponse\x12)\n" +
	"\x05lease\x18\x01 \x01(\v2\x13.pluginrpc.v1.LeaseR\x05lease\"E\n" +
	"\x05Lease\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12expires_unix_milli\x18\x02 \x01(\x03R\x10expiresUnixMilli\"=\n" +
	"\fRenewRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"ttl_millis\x18\x02 \x01(\x03R\tttlMillis\":\n" +
	"\rRenewResponse\x12)\n" +
	"\x05lease\x18\x01 \x01(\v2\x13.pluginrpc.v1.LeaseR\x05lease\"#\n" +
	"\x11UnregisterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12UnregisterResponse\"\x1a\n" +
	"\x18ListRegistrationsRequest\"]\n" +
	"\x19ListRegistrationsResponse\x12@\n" +
	"\rregistrations\x18\x01 \x03(\v2\x1a.pluginrpc.v1.RegistrationR\rregistrations*l\n" +
	"\rFailurePolicy\x12\x1e\n" +
	"\x1aFAILURE_POLICY_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aFAILURE_POLICY_FAIL_CLOSED\x10\x01\x12\x1b\n" +
	"\x17FAILURE_POLICY_CONTINUE\x10\x02*m\n" +
	"\n" +
	"ActionKind\x12\x1b\n" +
	"\x17ACTION_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ACTION_KIND_STEP\x10\x01\x12\x14\n" +
	"\x10ACTION_KIND_STOP\x10\x02\x12\x16\n" +
	"\x12ACTION_KIND_INJECT\x10\x03*\xc5\x01\n" +
	"\x0eOperationState\x12\x1f\n" +
	"\x1bOPERATION_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17OPERATION_STATE_PENDING\x10\x01\x12\x1b\n" +
	"\x17OPERATION_STATE_RUNNING\x10\x02\x12\x1d\n" +
	"\x19OPERATION_STATE_SUCCEEDED\x10\x03\x12\x1a\n" +
	"\x16OPERATION_STATE_FAILED\x10\x04\x12\x1d\n" +
	"\x19OPERATION_STATE_CANCELLED\x10\x05*\x84\x01\n" +
	"\rOperationKind\x12\x1e\n" +
	"\x1aOPERATION_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17OPERATION_KIND_PROVIDER\x10\x01\x12\x17\n" +
	"\x13OPERATION_KIND_TOOL\x10\x02\x12\x1d\n" +
	"\x19OPERATION_KIND_CAPABILITY\x10\x032\x8d\x04\n" +
	"\rPluginService\x12I\n" +
	"\bDescribe\x12\x1d.pluginrpc.v1.DescribeRequest\x1a\x1e.pluginrpc.v1.DescribeResponse\x12^\n" +
	"\x0fSubmitOperation\x12$.pluginrpc.v1.SubmitOperationRequest\x1a%.pluginrpc.v1.SubmitOperationResponse\x12X\n" +
	"\rPollOperation\x12\".pluginrpc.v1.PollOperationRequest\x1a#.pluginrpc.v1.PollOperationResponse\x12^\n" +
	"\x0fCancelOperation\x12$.pluginrpc.v1.CancelOperationRequest\x1a%.pluginrpc.v1.CancelOperationResponse\x12O\n" +
	"\n" +
	"HandleHook\x12\x1f.pluginrpc.v1.HandleHookRequest\x1a .pluginrpc.v1.HandleHookResponse\x12F\n" +
	"\aDeliver\x12\x1c.pluginrpc.v1.DeliverRequest\x1a\x1d.pluginrpc.v1.DeliverResponse2\xd5\x02\n" +
	"\x0fRegistryService\x12I\n" +
	"\bRegister\x12\x1d.pluginrpc.v1.RegisterRequest\x1a\x1e.pluginrpc.v1.RegisterResponse\x12@\n" +
	"\x05Renew\x12\x1a.pluginrpc.v1.RenewRequest\x1a\x1b.pluginrpc.v1.RenewResponse\x12O\n" +
	"\n" +
	"Unregister\x12\x1f.pluginrpc.v1.UnregisterRequest\x1a .pluginrpc.v1.UnregisterResponse\x12d\n" +
	"\x11ListRegistrations\x12&.pluginrpc.v1.ListRegistrationsRequest\x1a'.pluginrpc.v1.ListRegistrationsResponseB-Z+github.com/lincyaw/ag/pluginrpc/v1;pluginv1b\x06proto3"

var (
	file_pluginrpc_v1_plugin_proto_rawDescOnce sync.Once
	file_pluginrpc_v1_plugin_proto_rawDescData []byte
)

func file_pluginrpc_v1_plugin_proto_rawDescGZIP() []byte {
	file_pluginrpc_v1_plugin_proto_rawDescOnce.Do(func() {
		file_pluginrpc_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluginrpc_v1_plugin_proto_rawDesc), len(file_pluginrpc_v1_plugin_proto_rawDesc)))
	})
	return file_pluginrpc_v1_plugin_proto_rawDescData
}

var file_pluginrpc_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_pluginrpc_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_pluginrpc_v1_plugin_proto_goTypes = []any{
	(FailurePolicy)(0),                // 0: pluginrpc.v1.FailurePolicy
	(ActionKind)(0),                   // 1: pluginrpc.v1.ActionKind
	(OperationState)(0),               // 2: pluginrpc.v1.OperationState
	(OperationKind)(0),                // 3: pluginrpc.v1.OperationKind
	(*Manifest)(nil),                  // 4: pluginrpc.v1.Manifest
	(*ProviderSpec)(nil),              // 5: pluginrpc.v1.ProviderSpec
	(*ToolSpec)(nil),                  // 6: pluginrpc.v1.ToolSpec
	(*HookSpec)(nil),                  // 7: pluginrpc.v1.HookSpec
	(*SubscriberSpec)(nil),            // 8: pluginrpc.v1.SubscriberSpec
	(*CapabilitySpec)(nil),            // 9: pluginrpc.v1.CapabilitySpec
	(*EventContract)(nil),             // 10: pluginrpc.v1.EventContract
	(*DescribeResponse)(nil),          // 11: pluginrpc.v1.DescribeResponse
	(*DescribeRequest)(nil),           // 12: pluginrpc.v1.DescribeRequest
	(*ToolCall)(nil),                  // 13: pluginrpc.v1.ToolCall
	(*Message)(nil),                   // 14: pluginrpc.v1.Message
	(*Usage)(nil),                     // 15: pluginrpc.v1.Usage
	(*ModelRequest)(nil),              // 16: pluginrpc.v1.ModelRequest
	(*ModelResponse)(nil),             // 17: pluginrpc.v1.ModelResponse
	(*ToolResult)(nil),                // 18: pluginrpc.v1.ToolResult
	(*EventEnvelope)(nil),             // 19: pluginrpc.v1.EventEnvelope
	(*Block)(nil),                     // 20: pluginrpc.v1.Block
	(*Cause)(nil),                     // 21: pluginrpc.v1.Cause
	(*Action)(nil),                    // 22: pluginrpc.v1.Action
	(*Effect)(nil),                    // 23: pluginrpc.v1.Effect
	(*OperationRequest)(nil),          // 24: pluginrpc.v1.OperationRequest
	(*SubmitOperationRequest)(nil),    // 25: pluginrpc.v1.SubmitOperationRequest
	(*SubmitOperationResponse)(nil),   // 26: pluginrpc.v1.SubmitOperationResponse
	(*PollOperationRequest)(nil),      // 27: pluginrpc.v1.PollOperationRequest
	(*PollOperationResponse)(nil),     // 28: pluginrpc.v1.PollOperationResponse
	(*CancelOperationRequest)(nil),    // 29: pluginrpc.v1.CancelOperationRequest
	(*CancelOperationResponse)(nil),   // 30: pluginrpc.v1.CancelOperationResponse
	(*Operation)(nil),                 // 31: pluginrpc.v1.Operation
	(*HandleHookRequest)(nil),         // 32: pluginrpc.v1.HandleHookRequest
	(*HandleHookResponse)(nil),        // 33: pluginrpc.v1.HandleHookResponse
	(*Delivery)(nil),                  // 34: pluginrpc.v1.Delivery
	(*DeliverRequest)(nil),            // 35: pluginrpc.v1.DeliverRequest
	(*DeliverResponse)(nil),           // 36: pluginrpc.v1.DeliverResponse
	(*Registration)(nil),              // 37: pluginrpc.v1.Registration
	(*RegisterRequest)(nil),           // 38: pluginrpc.v1.RegisterRequest
	(*RegisterResponse)(nil),          // 39: pluginrpc.v1.RegisterResponse
	(*Lease)(nil),                     // 40: pluginrpc.v1.Lease
	(*RenewRequest)(nil),              // 41: pluginrpc.v1.RenewRequest
	(*RenewResponse)(nil),             // 42: pluginrpc.v1.RenewResponse
	(*UnregisterRequest)(nil),         // 43: pluginrpc.v1.UnregisterRequest
	(*UnregisterResponse)(nil),        // 44: pluginrpc.v1.UnregisterResponse
	(*ListRegistrationsRequest)(nil),  // 45: pluginrpc.v1.ListRegistrationsRequest
	(*ListRegistrationsResponse)(nil), // 46: pluginrpc.v1.ListRegistrationsResponse
	(*structpb.Struct)(nil),           // 47: google.protobuf.Struct
}
var file_pluginrpc_v1_plugin_proto_depIdxs = []int32{
	47, // 0: pluginrpc.v1.ToolSpec.parameters:type_name -> google.protobuf.Struct
	0,  // 1: pluginrpc.v1.HookSpec.failure_policy:type_name -> pluginrpc.v1.FailurePolicy
	47, // 2: pluginrpc.v1.CapabilitySpec.input_schema:type_name -> google.protobuf.Struct
	47, // 3: pluginrpc.v1.CapabilitySpec.output_schema:type_name -> google.protobuf.Struct
	4,  // 4: pluginrpc.v1.DescribeResponse.manifest:type_name -> pluginrpc.v1.Manifest
	5,  // 5: pluginrpc.v1.DescribeResponse.providers:type_name -> pluginrpc.v1.ProviderSpec
	6,  // 6: pluginrpc.v1.DescribeResponse.tools:type_name -> pluginrpc.v1.ToolSpec
	7,  // 7: pluginrpc.v1.DescribeResponse.hooks:type_name -> pluginrpc.v1.HookSpec
	9,  // 8: pluginrpc.v1.DescribeResponse.capabilities:type_name -> pluginrpc.v1.CapabilitySpec
	10, // 9: pluginrpc.v1.DescribeResponse.events:type_name -> pluginrpc.v1.EventContract
	8,  // 10: pluginrpc.v1.DescribeResponse.subscribers:type_name -> pluginrpc.v1.SubscriberSpec
	47, // 11: pluginrpc.v1.ToolCall.arguments:type_name -> google.protobuf.Struct
	13, // 12: pluginrpc.v1.Message.tool_calls:type_name -> pluginrpc.v1.ToolCall
	14, // 13: pluginrpc.v1.ModelRequest.messages:type_name -> pluginrpc.v1.Message
	6,  // 14: pluginrpc.v1.ModelRequest.tools:type_name -> pluginrpc.v1.ToolSpec
	13, // 15: pluginrpc.v1.ModelResponse.tool_calls:type_name -> pluginrpc.v1.ToolCall
	15, // 16: pluginrpc.v1.ModelResponse.usage:type_name -> pluginrpc.v1.Usage
	47, // 17: pluginrpc.v1.EventEnvelope.payload:type_name -> google.protobuf.Struct
	1,  // 18: pluginrpc.v1.Action.kind:type_name -> pluginrpc.v1.ActionKind
	21, // 19: pluginrpc.v1.Action.cause:type_name -> pluginrpc.v1.Cause
	14, // 20: pluginrpc.v1.Action.messages:type_name -> pluginrpc.v1.Message
	47, // 21: pluginrpc.v1.Effect.patch:type_name -> google.protobuf.Struct
	20, // 22: pluginrpc.v1.Effect.block:type_name -> pluginrpc.v1.Block
	22, // 23: pluginrpc.v1.Effect.action:type_name -> pluginrpc.v1.Action
	47, // 24: pluginrpc.v1.OperationRequest.input:type_name -> google.protobuf.Struct
	3,  // 25: pluginrpc.v1.SubmitOperationRequest.kind:type_name -> pluginrpc.v1.OperationKind
	24, // 26: pluginrpc.v1.SubmitOperationRequest.request:type_name -> pluginrpc.v1.OperationRequest
	31, // 27: pluginrpc.v1.SubmitOperationResponse.operation:type_name -> pluginrpc.v1.Operation
	3,  // 28: pluginrpc.v1.PollOperationRequest.kind:type_name -> pluginrpc.v1.OperationKind
	31, // 29: pluginrpc.v1.PollOperationResponse.operation:type_name -> pluginrpc.v1.Operation
	3,  // 30: pluginrpc.v1.CancelOperationRequest.kind:type_name -> pluginrpc.v1.OperationKind
	31, // 31: pluginrpc.v1.CancelOperationResponse.operation:type_name -> pluginrpc.v1.Operation
	2,  // 32: pluginrpc.v1.Operation.state:type_name -> pluginrpc.v1.OperationState
	47, // 33: pluginrpc.v1.Operation.output:type_name -> google.protobuf.Struct
	19, // 34: pluginrpc.v1.HandleHookRequest.event:type_name -> pluginrpc.v1.EventEnvelope
	23, // 35: pluginrpc.v1.HandleHookResponse.effect:type_name -> pluginrpc.v1.Effect
	19, // 36: pluginrpc.v1.Delivery.event:type_name -> pluginrpc.v1.EventEnvelope
	34, // 37: pluginrpc.v1.DeliverRequest.delivery:type_name -> pluginrpc.v1.Delivery
	4,  // 38: pluginrpc.v1.Registration.manifest:type_name -> pluginrpc.v1.Manifest
	37, // 39: pluginrpc.v1.RegisterRequest.registration:type_name -> pluginrpc.v1.Registration
	40, // 40: pluginrpc.v1.RegisterResponse.lease:type_name -> pluginrpc.v1.Lease
	40, // 41: pluginrpc.v1.RenewResponse.lease:type_name -> pluginrpc.v1.Lease
	37, // 42: pluginrpc.v1.ListRegistrationsResponse.registrations:type_name -> pluginrpc.v1.Registration
	12, // 43: pluginrpc.v1.PluginService.Describe:input_type -> pluginrpc.v1.DescribeRequest
	25, // 44: pluginrpc.v1.PluginService.SubmitOperation:input_type -> pluginrpc.v1.SubmitOperationRequest
	27, // 45: pluginrpc.v1.PluginService.PollOperation:input_type -> pluginrpc.v1.PollOperationRequest
	29, // 46: pluginrpc.v1.PluginService.CancelOperation:input_type -> pluginrpc.v1.CancelOperationRequest
	32, // 47: pluginrpc.v1.PluginService.HandleHook:input_type -> pluginrpc.v1.HandleHookRequest
	35, // 48: pluginrpc.v1.PluginService.Deliver:input_type -> pluginrpc.v1.DeliverRequest
	38, // 49: pluginrpc.v1.RegistryService.Register:input_type -> pluginrpc.v1.RegisterRequest
	41, // 50: pluginrpc.v1.RegistryService.Renew:input_type -> pluginrpc.v1.RenewRequest
	43, // 51: pluginrpc.v1.RegistryService.Unregister:input_type -> pluginrpc.v1.UnregisterRequest
	45, // 52: pluginrpc.v1.RegistryService.ListRegistrations:input_type -> pluginrpc.v1.ListRegistrationsRequest
	11, // 53: pluginrpc.v1.PluginService.Describe:output_type -> pluginrpc.v1.DescribeResponse
	26, // 54: pluginrpc.v1.PluginService.SubmitOperation:output_type -> pluginrpc.v1.SubmitOperationResponse
	28, // 55: pluginrpc.v1.PluginService.PollOperation:output_type -> pluginrpc.v1.PollOperationResponse
	30, // 56: pluginrpc.v1.PluginService.CancelOperation:output_type -> pluginrpc.v1.CancelOperationResponse
	33, // 57: pluginrpc.v1.PluginService.HandleHook:output_type -> pluginrpc.v1.HandleHookResponse
	36, // 58: pluginrpc.v1.PluginService.Deliver:output_type -> pluginrpc.v1.DeliverResponse
	39, // 59: pluginrpc.v1.RegistryService.Register:output_type -> pluginrpc.v1.RegisterResponse
	42, // 60: pluginrpc.v1.RegistryService.Renew:output_type -> pluginrpc.v1.RenewResponse
	44, // 61: pluginrpc.v1.RegistryService.Unregister:output_type -> pluginrpc.v1.UnregisterResponse
	46, // 62: pluginrpc.v1.RegistryService.ListRegistrations:output_type -> pluginrpc.v1.ListRegistrationsResponse
	53, // [53:63] is the sub-list for method output_type
	43, // [43:53] is the sub-list for method input_type
	43, // [43:43] is the sub-list for extension type_name
	43, // [43:43] is the sub-list for extension extendee
	0,  // [0:43] is the sub-list for field type_name
}

func init() { file_pluginrpc_v1_plugin_proto_init() }
func file_pluginrpc_v1_plugin_proto_init() {
	if File_pluginrpc_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluginrpc_v1_plugin_proto_rawDesc), len(file_pluginrpc_v1_plugin_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pluginrpc_v1_plugin_proto_goTypes,
		DependencyIndexes: file_pluginrpc_v1_plugin_proto_depIdxs,
		EnumInfos:         file_pluginrpc_v1_plugin_proto_enumTypes,
		MessageInfos:      file_pluginrpc_v1_plugin_proto_msgTypes,
	}.Build()
	File_pluginrpc_v1_plugin_proto = out.File
	file_pluginrpc_v1_plugin_proto_goTypes = nil
	file_pluginrpc_v1_plugin_proto_depIdxs = nil
}
